//
//  TONAccountState.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Blockchain state of an account at a given point in time.  The &#x60;status&#x60; field distinguishes four cases: - &#x60;active&#x60; — contract deployed, &#x60;code&#x60; and &#x60;data&#x60; present - &#x60;uninitialized&#x60; — has balance/history but no contract deployed; &#x60;code&#x60;/&#x60;data&#x60; omitted - &#x60;frozen&#x60; — frozen due to storage debt; &#x60;frozenHash&#x60; points at the pre-freeze state - &#x60;non-existing&#x60; — no on-chain record at all; balance is &#x60;&#39;0&#39;&#x60; and other fields omitted */

public struct TONAccountState: Codable {

    public var address: TONUserFriendlyAddress
    public var status: TONAccountStatus
    public var rawBalance: TONTokenAmount
    /** Balance formatted in GRAM (10^9 nano units = 1 GRAM). */
    public var balance: String
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var extraCurrencies: [String: String]
    /** Base64-encoded contract code BOC. Omitted if the contract is not deployed. */
    public var code: String?
    /** Base64-encoded contract data BOC. Omitted if the contract is not deployed. */
    public var data: String?
    public var lastTransaction: TONTransactionId?
    public var frozenHash: TONHex?

    public init(address: TONUserFriendlyAddress, status: TONAccountStatus, rawBalance: TONTokenAmount, balance: String, extraCurrencies: [String: String], code: String? = nil, data: String? = nil, lastTransaction: TONTransactionId? = nil, frozenHash: TONHex? = nil) {
        self.address = address
        self.status = status
        self.rawBalance = rawBalance
        self.balance = balance
        self.extraCurrencies = extraCurrencies
        self.code = code
        self.data = data
        self.lastTransaction = lastTransaction
        self.frozenHash = frozenHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case status
        case rawBalance
        case balance
        case extraCurrencies
        case code
        case data
        case lastTransaction
        case frozenHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(status, forKey: .status)
        try container.encode(rawBalance, forKey: .rawBalance)
        try container.encode(balance, forKey: .balance)
        try container.encode(extraCurrencies, forKey: .extraCurrencies)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(lastTransaction, forKey: .lastTransaction)
        try container.encodeIfPresent(frozenHash, forKey: .frozenHash)
    }
}




extension TONAccountState: JSValueCodable {}

