//
//  TONCryptoOnrampSourceCurrency.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** A source currency the user can spend to onramp into a TON asset. Always lives on a non-TON chain (identified by CAIP-2). */

public struct TONCryptoOnrampSourceCurrency: Codable {

    /** CAIP-2 source chain identifier, e.g. `'eip155:42161'`. */
    public var chain: String
    /** Token contract address on the source chain, or `'native'` for the chain's native gas coin. */
    public var address: String
    /** Token symbol, e.g. `'USDT0'`, `'ETH'`. */
    public var symbol: String
    /** Full token name, e.g. `'Tether USD0'`. Optional. */
    public var name: String?
    /** Decimals used to convert between display and base units. */
    public var decimals: Int
    /** Logo URL. */
    public var logo: String?

    public init(chain: String, address: String, symbol: String, name: String? = nil, decimals: Int, logo: String? = nil) {
        self.chain = chain
        self.address = address
        self.symbol = symbol
        self.name = name
        self.decimals = decimals
        self.logo = logo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chain
        case address
        case symbol
        case name
        case decimals
        case logo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chain, forKey: .chain)
        try container.encode(address, forKey: .address)
        try container.encode(symbol, forKey: .symbol)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(decimals, forKey: .decimals)
        try container.encodeIfPresent(logo, forKey: .logo)
    }
}




extension TONCryptoOnrampSourceCurrency: JSValueCodable {}

