//
//  TONConnectionRequestEventRequestedItem.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public enum TONConnectionRequestEventRequestedItem: Codable {

    case tonProof(TONConnectionRequestTonProofRequestedItem)
    case unknown(AnyCodable)
    case tonAddr

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)
        switch type {

        case "ton_proof":
            let value = try container.decode(TONConnectionRequestTonProofRequestedItem.self, forKey: .value)
            self = .tonProof(value)
        case "unknown":
            let value = try container.decode(AnyCodable.self, forKey: .value)
            self = .unknown(value)
        case "ton_addr":
            self = .tonAddr
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown type: \(type)"
            )
        }
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {

        case .tonProof(let value):
            try container.encode("ton_proof", forKey: .type)
            try container.encode(value, forKey: .value)
        case .unknown(let value):
            try container.encode("unknown", forKey: .type)
            try container.encode(value, forKey: .value)
        case .tonAddr:
            try container.encode("ton_addr", forKey: .type)
        }
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }
}



extension TONConnectionRequestEventRequestedItem: JSValueCodable {}

