//
//  TONCryptoOnrampProviderMetadata.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Static metadata for a crypto-onramp provider. */

public struct TONCryptoOnrampProviderMetadata: Codable {

    public enum RefundAddressMode: String, Codable, CaseIterable {
        case off = "off"
        case `optional` = "optional"
        case `required` = "required"
    }    /** Human-readable provider name (e.g. 'Decent') */
    public var name: String
    /** URL to the provider's logo image */
    public var logo: String?
    /** URL to the provider's website */
    public var url: String?
    /** Refund-address collection mode for this provider: - `'off'` (default): no refund address — the UI skips the address modal entirely. - `'optional'`: the UI shows the address modal with a \"Skip\" button — users may   enter an address or proceed without one. - `'required'`: the UI shows the address modal and blocks submission until a   non-empty address is entered. */
    public var refundAddressMode: RefundAddressMode?
    /** Whether this provider supports reversed (target-amount) quotes. When false, the UI should hide the direction toggle and only allow source-amount input. */
    public var isReversedAmountSupported: Bool?

    public init(name: String, logo: String? = nil, url: String? = nil, refundAddressMode: RefundAddressMode? = nil, isReversedAmountSupported: Bool? = nil) {
        self.name = name
        self.logo = logo
        self.url = url
        self.refundAddressMode = refundAddressMode
        self.isReversedAmountSupported = isReversedAmountSupported
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case logo
        case url
        case refundAddressMode
        case isReversedAmountSupported
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(refundAddressMode, forKey: .refundAddressMode)
        try container.encodeIfPresent(isReversedAmountSupported, forKey: .isReversedAmountSupported)
    }
}




extension TONCryptoOnrampProviderMetadata: JSValueCodable {}

