//
//  TONCryptoOnrampDeposit.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Deposit details returned by a crypto onramp provider.  The user must send &#x60;amount&#x60; of &#x60;sourceCurrency&#x60; to &#x60;address&#x60; to complete the onramp; the provider then delivers the target crypto to the user&#39;s TON address. */

public struct TONCryptoOnrampDeposit: Codable {

    /** Deposit id */
    public var depositId: String
    /** Deposit address on the source chain */
    public var address: String
    /** Exact amount of source crypto the user must send (in base units of `sourceCurrency.decimals`). */
    public var amount: String
    public var sourceCurrency: TONCryptoOnrampSourceCurrency
    /** Optional memo / tag required by some chains (e.g. XRP, TON comment) */
    public var memo: String?
    /** Unix timestamp (ms) after which the deposit offer is no longer valid */
    public var expiresAt: Double?
    /** Identifier of the provider that issued this deposit */
    public var providerId: String

    public init(depositId: String, address: String, amount: String, sourceCurrency: TONCryptoOnrampSourceCurrency, memo: String? = nil, expiresAt: Double? = nil, providerId: String) {
        self.depositId = depositId
        self.address = address
        self.amount = amount
        self.sourceCurrency = sourceCurrency
        self.memo = memo
        self.expiresAt = expiresAt
        self.providerId = providerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case depositId
        case address
        case amount
        case sourceCurrency
        case memo
        case expiresAt
        case providerId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(depositId, forKey: .depositId)
        try container.encode(address, forKey: .address)
        try container.encode(amount, forKey: .amount)
        try container.encode(sourceCurrency, forKey: .sourceCurrency)
        try container.encodeIfPresent(memo, forKey: .memo)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encode(providerId, forKey: .providerId)
    }
}




extension TONCryptoOnrampDeposit: JSValueCodable {}

