//
//  TONCryptoOnrampQuoteParams.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public struct TONCryptoOnrampQuoteParams<TProviderOptions: Codable>: Codable {
    /** Amount to onramp (either source or target crypto, depending on isSourceAmount) */
    public var amount: String
    public var sourceCurrency: TONCryptoOnrampSourceCurrency
    public var targetCurrency: TONCryptoOnrampDestinationCurrency
    /** TON address that will receive the target crypto */
    public var recipientAddress: String
    /** Refund address for the source crypto */
    public var refundAddress: String?
    /** If true, `amount` is the source amount to spend. If false, `amount` is the target amount to receive. Defaults to true when omitted. */
    public var isSourceAmount: Bool?
    /** Provider-specific options */
    public var providerOptions: TProviderOptions?

    public init(amount: String, sourceCurrency: TONCryptoOnrampSourceCurrency, targetCurrency: TONCryptoOnrampDestinationCurrency, recipientAddress: String, refundAddress: String? = nil, isSourceAmount: Bool? = nil, providerOptions: TProviderOptions? = nil) {
        self.amount = amount
        self.sourceCurrency = sourceCurrency
        self.targetCurrency = targetCurrency
        self.recipientAddress = recipientAddress
        self.refundAddress = refundAddress
        self.isSourceAmount = isSourceAmount
        self.providerOptions = providerOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case sourceCurrency
        case targetCurrency
        case recipientAddress
        case refundAddress
        case isSourceAmount
        case providerOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(sourceCurrency, forKey: .sourceCurrency)
        try container.encode(targetCurrency, forKey: .targetCurrency)
        try container.encode(recipientAddress, forKey: .recipientAddress)
        try container.encodeIfPresent(refundAddress, forKey: .refundAddress)
        try container.encodeIfPresent(isSourceAmount, forKey: .isSourceAmount)
        try container.encodeIfPresent(providerOptions, forKey: .providerOptions)
    }
}



extension TONCryptoOnrampQuoteParams: JSValueCodable {}

