//
//  TONCryptoOnrampQuote.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public struct TONCryptoOnrampQuote<TMetadata: Codable>: Codable {
    public var sourceCurrency: TONCryptoOnrampSourceCurrency
    public var targetCurrency: TONCryptoOnrampDestinationCurrency
    /** Amount of source crypto to send (in base units of `sourceCurrency.decimals`). */
    public var sourceAmount: Int
    /** Amount of target crypto to receive (in base units of `targetCurrency.decimals`). */
    public var targetAmount: Int
    /** Exchange rate (amount of target per 1 unit of source) */
    public var rate: String
    /** TON address that will receive the target crypto */
    public var recipientAddress: String
    /** Identifier of the crypto onramp provider */
    public var providerId: String
    /** Provider-specific metadata for the quote (e.g. raw response needed to execute) */
    public var metadata: TMetadata?

    public init(sourceCurrency: TONCryptoOnrampSourceCurrency, targetCurrency: TONCryptoOnrampDestinationCurrency, sourceAmount: Int, targetAmount: Int, rate: String, recipientAddress: String, providerId: String, metadata: TMetadata? = nil) {
        self.sourceCurrency = sourceCurrency
        self.targetCurrency = targetCurrency
        self.sourceAmount = sourceAmount
        self.targetAmount = targetAmount
        self.rate = rate
        self.recipientAddress = recipientAddress
        self.providerId = providerId
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sourceCurrency
        case targetCurrency
        case sourceAmount
        case targetAmount
        case rate
        case recipientAddress
        case providerId
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sourceCurrency, forKey: .sourceCurrency)
        try container.encode(targetCurrency, forKey: .targetCurrency)
        try container.encode(sourceAmount, forKey: .sourceAmount)
        try container.encode(targetAmount, forKey: .targetAmount)
        try container.encode(rate, forKey: .rate)
        try container.encode(recipientAddress, forKey: .recipientAddress)
        try container.encode(providerId, forKey: .providerId)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}



extension TONCryptoOnrampQuote: JSValueCodable {}

