//
//  TONDeDustRouteStep.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Route step from DeDust Router API */

public struct TONDeDustRouteStep: Codable {

    public var poolAddress: String
    public var isStable: Bool
    public var inMinter: String
    public var outMinter: String
    public var inAmount: String
    public var outAmount: String
    public var networkFee: String
    public var protocolSlug: String
    public var stonfiExtraDetails: TONDeDustRouteStepStonfiExtraDetails?

    public init(poolAddress: String, isStable: Bool, inMinter: String, outMinter: String, inAmount: String, outAmount: String, networkFee: String, protocolSlug: String, stonfiExtraDetails: TONDeDustRouteStepStonfiExtraDetails? = nil) {
        self.poolAddress = poolAddress
        self.isStable = isStable
        self.inMinter = inMinter
        self.outMinter = outMinter
        self.inAmount = inAmount
        self.outAmount = outAmount
        self.networkFee = networkFee
        self.protocolSlug = protocolSlug
        self.stonfiExtraDetails = stonfiExtraDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case poolAddress = "pool_address"
        case isStable = "is_stable"
        case inMinter = "in_minter"
        case outMinter = "out_minter"
        case inAmount = "in_amount"
        case outAmount = "out_amount"
        case networkFee = "network_fee"
        case protocolSlug = "protocol_slug"
        case stonfiExtraDetails = "stonfi_extra_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(poolAddress, forKey: .poolAddress)
        try container.encode(isStable, forKey: .isStable)
        try container.encode(inMinter, forKey: .inMinter)
        try container.encode(outMinter, forKey: .outMinter)
        try container.encode(inAmount, forKey: .inAmount)
        try container.encode(outAmount, forKey: .outAmount)
        try container.encode(networkFee, forKey: .networkFee)
        try container.encode(protocolSlug, forKey: .protocolSlug)
        try container.encodeIfPresent(stonfiExtraDetails, forKey: .stonfiExtraDetails)
    }
}




extension TONDeDustRouteStep: JSValueCodable {}

