//
//  TONDAppInfo.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Information about a decentralized application (dApp) connecting via TON Connect. */

public struct TONDAppInfo: Codable {

    /** Display name of the dApp */
    public var name: String?
    /** Brief description of the dApp's purpose */
    public var description: String?
    /** Main website URL of the dApp */
    public var url: URL?
    /** Icon/logo URL of the dApp */
    public var iconUrl: URL?
    /** Manifest URL of the dApp */
    public var manifestUrl: URL?

    public init(name: String? = nil, description: String? = nil, url: URL? = nil, iconUrl: URL? = nil, manifestUrl: URL? = nil) {
        self.name = name
        self.description = description
        self.url = url
        self.iconUrl = iconUrl
        self.manifestUrl = manifestUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case url
        case iconUrl
        case manifestUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(iconUrl, forKey: .iconUrl)
        try container.encodeIfPresent(manifestUrl, forKey: .manifestUrl)
    }
}




extension TONDAppInfo: JSValueCodable {}

