//
//  TONDeDustQuoteResponse.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Quote response from DeDust Router API */

public struct TONDeDustQuoteResponse: Codable {

    public var inAmount: String
    public var outAmount: String
    public var swapData: TONDeDustSwapData
    public var swapIsPossible: Bool
    public var priceImpact: Double?
    public var improvement: String?
    public var inMinterPrice: String?
    public var outMinterPrice: String?

    public init(inAmount: String, outAmount: String, swapData: TONDeDustSwapData, swapIsPossible: Bool, priceImpact: Double? = nil, improvement: String? = nil, inMinterPrice: String? = nil, outMinterPrice: String? = nil) {
        self.inAmount = inAmount
        self.outAmount = outAmount
        self.swapData = swapData
        self.swapIsPossible = swapIsPossible
        self.priceImpact = priceImpact
        self.improvement = improvement
        self.inMinterPrice = inMinterPrice
        self.outMinterPrice = outMinterPrice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inAmount = "in_amount"
        case outAmount = "out_amount"
        case swapData = "swap_data"
        case swapIsPossible = "swap_is_possible"
        case priceImpact = "price_impact"
        case improvement
        case inMinterPrice = "in_minter_price"
        case outMinterPrice = "out_minter_price"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inAmount, forKey: .inAmount)
        try container.encode(outAmount, forKey: .outAmount)
        try container.encode(swapData, forKey: .swapData)
        try container.encode(swapIsPossible, forKey: .swapIsPossible)
        try container.encodeIfPresent(priceImpact, forKey: .priceImpact)
        try container.encodeIfPresent(improvement, forKey: .improvement)
        try container.encodeIfPresent(inMinterPrice, forKey: .inMinterPrice)
        try container.encodeIfPresent(outMinterPrice, forKey: .outMinterPrice)
    }
}




extension TONDeDustQuoteResponse: JSValueCodable {}

