//
//  TONDeDustSwapProviderConfig.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Configuration for the DeDust Swap Provider */

public struct TONDeDustSwapProviderConfig: Codable {

    /** The address of the referrer */
    public var referralAddress: String?
    /** Referral fee in basis points (max 100 = 1%) */
    public var referralFeeBps: Int?
    /** Custom provider ID (defaults to 'dedust') */
    public var providerId: String?
    /** Default slippage tolerance in basis points (1 bp = 0.01%) */
    public var defaultSlippageBps: Int?
    /** API base URL */
    public var apiUrl: URL?
    /** Only use verified pools */
    public var onlyVerifiedPools: Bool?
    /** Maximum number of route splits */
    public var maxSplits: Int?
    /** Maximum route length (hops) */
    public var maxLength: Int?
    /** Minimum pool TVL in USD */
    public var minPoolUsdTvl: String?
    public var metadata: TONSwapProviderMetadataOverride?

    public init(referralAddress: String? = nil, referralFeeBps: Int? = nil, providerId: String? = nil, defaultSlippageBps: Int? = nil, apiUrl: URL? = nil, onlyVerifiedPools: Bool? = nil, maxSplits: Int? = nil, maxLength: Int? = nil, minPoolUsdTvl: String? = nil, metadata: TONSwapProviderMetadataOverride? = nil) {
        self.referralAddress = referralAddress
        self.referralFeeBps = referralFeeBps
        self.providerId = providerId
        self.defaultSlippageBps = defaultSlippageBps
        self.apiUrl = apiUrl
        self.onlyVerifiedPools = onlyVerifiedPools
        self.maxSplits = maxSplits
        self.maxLength = maxLength
        self.minPoolUsdTvl = minPoolUsdTvl
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referralAddress
        case referralFeeBps
        case providerId
        case defaultSlippageBps
        case apiUrl
        case onlyVerifiedPools
        case maxSplits
        case maxLength
        case minPoolUsdTvl
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(referralAddress, forKey: .referralAddress)
        try container.encodeIfPresent(referralFeeBps, forKey: .referralFeeBps)
        try container.encodeIfPresent(providerId, forKey: .providerId)
        try container.encodeIfPresent(defaultSlippageBps, forKey: .defaultSlippageBps)
        try container.encodeIfPresent(apiUrl, forKey: .apiUrl)
        try container.encodeIfPresent(onlyVerifiedPools, forKey: .onlyVerifiedPools)
        try container.encodeIfPresent(maxSplits, forKey: .maxSplits)
        try container.encodeIfPresent(maxLength, forKey: .maxLength)
        try container.encodeIfPresent(minPoolUsdTvl, forKey: .minPoolUsdTvl)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}




extension TONDeDustSwapProviderConfig: JSValueCodable {}

