//
//  TONDeDustProviderOptions.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Provider-specific options for DeDust swap operations */

public struct TONDeDustProviderOptions: Codable {

    /** The address of the referrer */
    public var referralAddress: String?
    /** Referral fee in basis points (max 100 = 1%) */
    public var referralFeeBps: Int?
    /** Protocols to use for routing Available: 'dedust', 'dedust_v3', 'dedust_v3_memepad', 'stonfi_v1', 'stonfi_v2', 'tonco', 'memeslab', 'tonfun' */
    public var protocols: [String]?
    /** Protocols to exclude from routing */
    public var excludeProtocols: [String]?
    /** Only use verified pools */
    public var onlyVerifiedPools: Bool?
    /** Maximum number of route splits */
    public var maxSplits: Int?
    /** Maximum route length (hops) */
    public var maxLength: Int?
    /** Exclude volatile pools */
    public var excludeVolatilePools: Bool?

    public init(referralAddress: String? = nil, referralFeeBps: Int? = nil, protocols: [String]? = nil, excludeProtocols: [String]? = nil, onlyVerifiedPools: Bool? = nil, maxSplits: Int? = nil, maxLength: Int? = nil, excludeVolatilePools: Bool? = nil) {
        self.referralAddress = referralAddress
        self.referralFeeBps = referralFeeBps
        self.protocols = protocols
        self.excludeProtocols = excludeProtocols
        self.onlyVerifiedPools = onlyVerifiedPools
        self.maxSplits = maxSplits
        self.maxLength = maxLength
        self.excludeVolatilePools = excludeVolatilePools
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referralAddress
        case referralFeeBps
        case protocols
        case excludeProtocols
        case onlyVerifiedPools
        case maxSplits
        case maxLength
        case excludeVolatilePools
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(referralAddress, forKey: .referralAddress)
        try container.encodeIfPresent(referralFeeBps, forKey: .referralFeeBps)
        try container.encodeIfPresent(protocols, forKey: .protocols)
        try container.encodeIfPresent(excludeProtocols, forKey: .excludeProtocols)
        try container.encodeIfPresent(onlyVerifiedPools, forKey: .onlyVerifiedPools)
        try container.encodeIfPresent(maxSplits, forKey: .maxSplits)
        try container.encodeIfPresent(maxLength, forKey: .maxLength)
        try container.encodeIfPresent(excludeVolatilePools, forKey: .excludeVolatilePools)
    }
}




extension TONDeDustProviderOptions: JSValueCodable {}

