//
//  TONEmulationResult.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public enum TONEmulationResult: Codable {

    case success(emulationResult: TONEmulationResponse)

    case error(emulationError: TONEmulationError)


    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .discriminator)
        switch discriminator {

        case "success":
            let emulationResult = try container.decode(TONEmulationResponse.self, forKey: .emulationResult)
            self = .success(emulationResult: emulationResult)

        case "error":
            let emulationError = try container.decode(TONEmulationError.self, forKey: .emulationError)
            self = .error(emulationError: emulationError)

        default:
            throw DecodingError.dataCorruptedError(
                forKey: .discriminator,
                in: container,
                debugDescription: "Unknown discriminator value: \(discriminator)"
            )
        }
    }

    public func encode(to encoder: any Encoder) throws {
        switch self {

        case .success(let emulationResult):
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode("success", forKey: .discriminator)
            try container.encode(emulationResult, forKey: .emulationResult)

        case .error(let emulationError):
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode("error", forKey: .discriminator)
            try container.encode(emulationError, forKey: .emulationError)

        }
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discriminator = "result"
        case emulationResult
        case emulationError
    }
}



extension TONEmulationResult: JSValueCodable {}

