//
//  TONEmulationActionPhase.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Action phase of transaction execution (outgoing message sending). */

public struct TONEmulationActionPhase: Codable {

    /** Whether the action phase succeeded */
    public var isSuccess: Bool
    /** Whether the action list was valid */
    public var isValid: Bool
    /** Whether the transaction failed due to insufficient funds */
    public var hasNoFunds: Bool
    /** Account status change applied during the action phase */
    public var statusChange: String
    public var totalFwdFees: TONTokenAmount?
    public var totalActionFees: TONTokenAmount?
    /** Result code of the action phase */
    public var resultCode: Int
    /** Total number of actions processed */
    public var totalActions: Int
    /** Number of special actions executed */
    public var specActions: Int
    /** Number of actions skipped */
    public var skippedActions: Int
    /** Number of messages created */
    public var msgsCreated: Int
    public var actionListHash: TONHex?
    public var totalMsgSize: TONEmulationActionMessageSize

    public init(isSuccess: Bool, isValid: Bool, hasNoFunds: Bool, statusChange: String, totalFwdFees: TONTokenAmount? = nil, totalActionFees: TONTokenAmount? = nil, resultCode: Int, totalActions: Int, specActions: Int, skippedActions: Int, msgsCreated: Int, actionListHash: TONHex? = nil, totalMsgSize: TONEmulationActionMessageSize) {
        self.isSuccess = isSuccess
        self.isValid = isValid
        self.hasNoFunds = hasNoFunds
        self.statusChange = statusChange
        self.totalFwdFees = totalFwdFees
        self.totalActionFees = totalActionFees
        self.resultCode = resultCode
        self.totalActions = totalActions
        self.specActions = specActions
        self.skippedActions = skippedActions
        self.msgsCreated = msgsCreated
        self.actionListHash = actionListHash
        self.totalMsgSize = totalMsgSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSuccess
        case isValid
        case hasNoFunds
        case statusChange
        case totalFwdFees
        case totalActionFees
        case resultCode
        case totalActions
        case specActions
        case skippedActions
        case msgsCreated
        case actionListHash
        case totalMsgSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isSuccess, forKey: .isSuccess)
        try container.encode(isValid, forKey: .isValid)
        try container.encode(hasNoFunds, forKey: .hasNoFunds)
        try container.encode(statusChange, forKey: .statusChange)
        try container.encodeIfPresent(totalFwdFees, forKey: .totalFwdFees)
        try container.encodeIfPresent(totalActionFees, forKey: .totalActionFees)
        try container.encode(resultCode, forKey: .resultCode)
        try container.encode(totalActions, forKey: .totalActions)
        try container.encode(specActions, forKey: .specActions)
        try container.encode(skippedActions, forKey: .skippedActions)
        try container.encode(msgsCreated, forKey: .msgsCreated)
        try container.encodeIfPresent(actionListHash, forKey: .actionListHash)
        try container.encode(totalMsgSize, forKey: .totalMsgSize)
    }
}




extension TONEmulationActionPhase: JSValueCodable {}

