//
//  TONEmulationMessageContent.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Decoded content of an emulation message body. */

public struct TONEmulationMessageContent: Codable {

    public var hash: TONHex?
    public var body: TONBase64?
    /** Structured decoded representation of the message body, if available */
    public var decoded: AnyCodable?

    public init(hash: TONHex? = nil, body: TONBase64? = nil, decoded: AnyCodable? = nil) {
        self.hash = hash
        self.body = body
        self.decoded = decoded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hash
        case body
        case decoded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hash, forKey: .hash)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(decoded, forKey: .decoded)
    }
}




extension TONEmulationMessageContent: JSValueCodable {}

