//
//  TONEmulationTransaction.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Transaction within an emulated trace. */

public struct TONEmulationTransaction: Codable {

    public var account: TONUserFriendlyAddress
    public var hash: TONHex
    public var lt: String
    /** Unix timestamp of the transaction */
    public var now: Int
    /** Masterchain block sequence number */
    public var mcBlockSeqno: Int
    public var traceExternalHash: TONHex
    public var prevTransHash: TONHex?
    public var prevTransLt: String?
    public var origStatus: TONAccountStatus
    public var endStatus: TONAccountStatus
    public var totalFees: TONTokenAmount
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var totalFeesExtraCurrencies: [String: String]
    public var description: TONEmulationTransactionDescription
    public var blockRef: TONEmulationBlockRef
    public var inMsg: TONEmulationMessage?
    /** Outgoing messages produced by this transaction */
    public var outMsgs: [TONEmulationMessage]
    public var accountStateBefore: TONEmulationAccountState
    public var accountStateAfter: TONEmulationAccountState
    /** Whether this transaction was produced by emulation rather than executed on-chain */
    public var isEmulated: Bool
    /** Trace identifier, if available */
    public var traceId: String?

    public init(account: TONUserFriendlyAddress, hash: TONHex, lt: String, now: Int, mcBlockSeqno: Int, traceExternalHash: TONHex, prevTransHash: TONHex? = nil, prevTransLt: String? = nil, origStatus: TONAccountStatus, endStatus: TONAccountStatus, totalFees: TONTokenAmount, totalFeesExtraCurrencies: [String: String], description: TONEmulationTransactionDescription, blockRef: TONEmulationBlockRef, inMsg: TONEmulationMessage? = nil, outMsgs: [TONEmulationMessage], accountStateBefore: TONEmulationAccountState, accountStateAfter: TONEmulationAccountState, isEmulated: Bool, traceId: String? = nil) {
        self.account = account
        self.hash = hash
        self.lt = lt
        self.now = now
        self.mcBlockSeqno = mcBlockSeqno
        self.traceExternalHash = traceExternalHash
        self.prevTransHash = prevTransHash
        self.prevTransLt = prevTransLt
        self.origStatus = origStatus
        self.endStatus = endStatus
        self.totalFees = totalFees
        self.totalFeesExtraCurrencies = totalFeesExtraCurrencies
        self.description = description
        self.blockRef = blockRef
        self.inMsg = inMsg
        self.outMsgs = outMsgs
        self.accountStateBefore = accountStateBefore
        self.accountStateAfter = accountStateAfter
        self.isEmulated = isEmulated
        self.traceId = traceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case hash
        case lt
        case now
        case mcBlockSeqno
        case traceExternalHash
        case prevTransHash
        case prevTransLt
        case origStatus
        case endStatus
        case totalFees
        case totalFeesExtraCurrencies
        case description
        case blockRef
        case inMsg
        case outMsgs
        case accountStateBefore
        case accountStateAfter
        case isEmulated
        case traceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encode(hash, forKey: .hash)
        try container.encode(lt, forKey: .lt)
        try container.encode(now, forKey: .now)
        try container.encode(mcBlockSeqno, forKey: .mcBlockSeqno)
        try container.encode(traceExternalHash, forKey: .traceExternalHash)
        try container.encodeIfPresent(prevTransHash, forKey: .prevTransHash)
        try container.encodeIfPresent(prevTransLt, forKey: .prevTransLt)
        try container.encode(origStatus, forKey: .origStatus)
        try container.encode(endStatus, forKey: .endStatus)
        try container.encode(totalFees, forKey: .totalFees)
        try container.encode(totalFeesExtraCurrencies, forKey: .totalFeesExtraCurrencies)
        try container.encode(description, forKey: .description)
        try container.encode(blockRef, forKey: .blockRef)
        try container.encodeIfPresent(inMsg, forKey: .inMsg)
        try container.encode(outMsgs, forKey: .outMsgs)
        try container.encode(accountStateBefore, forKey: .accountStateBefore)
        try container.encode(accountStateAfter, forKey: .accountStateAfter)
        try container.encode(isEmulated, forKey: .isEmulated)
        try container.encodeIfPresent(traceId, forKey: .traceId)
    }
}




extension TONEmulationTransaction: JSValueCodable {}

