//
//  TONEmulationAction.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** High-level action extracted from an emulated transaction trace. */

public struct TONEmulationAction: Codable {

    /** Trace identifier this action belongs to */
    public var traceId: String?
    public var actionId: TONHex
    public var startLt: String
    public var endLt: String
    /** Unix timestamp when the action started */
    public var startUtime: Int
    /** Unix timestamp when the action ended */
    public var endUtime: Int
    public var traceEndLt: String
    /** Unix timestamp when the trace ended */
    public var traceEndUtime: Int
    /** Masterchain block sequence number when the trace ended */
    public var traceMcSeqnoEnd: Int
    /** Hex-encoded hashes of transactions involved in this action */
    public var transactions: [TONHex]
    /** Whether the action completed successfully */
    public var isSuccess: Bool
    /** Action type identifier (e.g. \"jetton_transfer\", \"ton_transfer\", \"jetton_swap\") */
    public var type: String
    public var traceExternalHash: TONHex
    /** Addresses of accounts involved in this action */
    public var accounts: [TONUserFriendlyAddress]
    /** Action-specific detail fields keyed by name */
    public var details: [String: AnyCodable]

    public init(traceId: String? = nil, actionId: TONHex, startLt: String, endLt: String, startUtime: Int, endUtime: Int, traceEndLt: String, traceEndUtime: Int, traceMcSeqnoEnd: Int, transactions: [TONHex], isSuccess: Bool, type: String, traceExternalHash: TONHex, accounts: [TONUserFriendlyAddress], details: [String: AnyCodable]) {
        self.traceId = traceId
        self.actionId = actionId
        self.startLt = startLt
        self.endLt = endLt
        self.startUtime = startUtime
        self.endUtime = endUtime
        self.traceEndLt = traceEndLt
        self.traceEndUtime = traceEndUtime
        self.traceMcSeqnoEnd = traceMcSeqnoEnd
        self.transactions = transactions
        self.isSuccess = isSuccess
        self.type = type
        self.traceExternalHash = traceExternalHash
        self.accounts = accounts
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case traceId
        case actionId
        case startLt
        case endLt
        case startUtime
        case endUtime
        case traceEndLt
        case traceEndUtime
        case traceMcSeqnoEnd
        case transactions
        case isSuccess
        case type
        case traceExternalHash
        case accounts
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(traceId, forKey: .traceId)
        try container.encode(actionId, forKey: .actionId)
        try container.encode(startLt, forKey: .startLt)
        try container.encode(endLt, forKey: .endLt)
        try container.encode(startUtime, forKey: .startUtime)
        try container.encode(endUtime, forKey: .endUtime)
        try container.encode(traceEndLt, forKey: .traceEndLt)
        try container.encode(traceEndUtime, forKey: .traceEndUtime)
        try container.encode(traceMcSeqnoEnd, forKey: .traceMcSeqnoEnd)
        try container.encode(transactions, forKey: .transactions)
        try container.encode(isSuccess, forKey: .isSuccess)
        try container.encode(type, forKey: .type)
        try container.encode(traceExternalHash, forKey: .traceExternalHash)
        try container.encode(accounts, forKey: .accounts)
        try container.encode(details, forKey: .details)
    }
}




extension TONEmulationAction: JSValueCodable {}

