//
//  TONEmulationTransactionDescription.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Detailed description of all execution phases in an emulated transaction. */

public struct TONEmulationTransactionDescription: Codable {

    /** Transaction type (e.g. \"ord\", \"ticktock\", \"storage\") */
    public var type: String
    /** Whether the transaction was aborted */
    public var isAborted: Bool
    /** Whether the account was destroyed by this transaction */
    public var isDestroyed: Bool
    /** Whether the credit phase was executed before the storage phase */
    public var isCreditFirst: Bool
    /** Whether this was a tock transaction */
    public var isTock: Bool
    /** Whether a contract was installed in this transaction */
    public var isInstalled: Bool
    public var storagePhase: TONEmulationStoragePhase
    public var creditPhase: TONEmulationCreditPhase?
    public var computePhase: TONEmulationComputePhase
    public var actionPhase: TONEmulationActionPhase?

    public init(type: String, isAborted: Bool, isDestroyed: Bool, isCreditFirst: Bool, isTock: Bool, isInstalled: Bool, storagePhase: TONEmulationStoragePhase, creditPhase: TONEmulationCreditPhase? = nil, computePhase: TONEmulationComputePhase, actionPhase: TONEmulationActionPhase? = nil) {
        self.type = type
        self.isAborted = isAborted
        self.isDestroyed = isDestroyed
        self.isCreditFirst = isCreditFirst
        self.isTock = isTock
        self.isInstalled = isInstalled
        self.storagePhase = storagePhase
        self.creditPhase = creditPhase
        self.computePhase = computePhase
        self.actionPhase = actionPhase
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case isAborted
        case isDestroyed
        case isCreditFirst
        case isTock
        case isInstalled
        case storagePhase
        case creditPhase
        case computePhase
        case actionPhase
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(isAborted, forKey: .isAborted)
        try container.encode(isDestroyed, forKey: .isDestroyed)
        try container.encode(isCreditFirst, forKey: .isCreditFirst)
        try container.encode(isTock, forKey: .isTock)
        try container.encode(isInstalled, forKey: .isInstalled)
        try container.encode(storagePhase, forKey: .storagePhase)
        try container.encodeIfPresent(creditPhase, forKey: .creditPhase)
        try container.encode(computePhase, forKey: .computePhase)
        try container.encodeIfPresent(actionPhase, forKey: .actionPhase)
    }
}




extension TONEmulationTransactionDescription: JSValueCodable {}

