//
//  TONEmulationAccountState.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** State of an account at a specific point in an emulated transaction. */

public struct TONEmulationAccountState: Codable {

    public var hash: TONHex?
    public var balance: TONTokenAmount
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var extraCurrencies: [String: String]?
    public var accountStatus: TONAccountStatus
    public var frozenHash: TONHex?
    public var dataHash: TONHex?
    public var codeHash: TONHex?

    public init(hash: TONHex? = nil, balance: TONTokenAmount, extraCurrencies: [String: String]? = nil, accountStatus: TONAccountStatus, frozenHash: TONHex? = nil, dataHash: TONHex? = nil, codeHash: TONHex? = nil) {
        self.hash = hash
        self.balance = balance
        self.extraCurrencies = extraCurrencies
        self.accountStatus = accountStatus
        self.frozenHash = frozenHash
        self.dataHash = dataHash
        self.codeHash = codeHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hash
        case balance
        case extraCurrencies
        case accountStatus
        case frozenHash
        case dataHash
        case codeHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hash, forKey: .hash)
        try container.encode(balance, forKey: .balance)
        try container.encodeIfPresent(extraCurrencies, forKey: .extraCurrencies)
        try container.encode(accountStatus, forKey: .accountStatus)
        try container.encodeIfPresent(frozenHash, forKey: .frozenHash)
        try container.encodeIfPresent(dataHash, forKey: .dataHash)
        try container.encodeIfPresent(codeHash, forKey: .codeHash)
    }
}




extension TONEmulationAccountState: JSValueCodable {}

