//
//  TONEmulationComputePhase.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Compute phase of transaction execution (TVM execution). */

public struct TONEmulationComputePhase: Codable {

    /** Whether the compute phase was skipped */
    public var isSkipped: Bool
    /** Whether the TVM execution succeeded */
    public var isSuccess: Bool
    /** Whether the message state was used during compute */
    public var isMsgStateUsed: Bool
    /** Whether the account was activated during compute */
    public var isAccountActivated: Bool
    public var gasFees: TONTokenAmount
    /** Total gas consumed */
    public var gasUsed: String
    /** Gas limit for this execution */
    public var gasLimit: String
    /** Gas credit, if any */
    public var gasCredit: String?
    /** Compute execution mode */
    public var mode: Int
    /** TVM exit code */
    public var exitCode: Int
    /** Number of TVM steps executed */
    public var vmSteps: Int
    public var vmInitStateHash: TONHex?
    public var vmFinalStateHash: TONHex?

    public init(isSkipped: Bool, isSuccess: Bool, isMsgStateUsed: Bool, isAccountActivated: Bool, gasFees: TONTokenAmount, gasUsed: String, gasLimit: String, gasCredit: String? = nil, mode: Int, exitCode: Int, vmSteps: Int, vmInitStateHash: TONHex? = nil, vmFinalStateHash: TONHex? = nil) {
        self.isSkipped = isSkipped
        self.isSuccess = isSuccess
        self.isMsgStateUsed = isMsgStateUsed
        self.isAccountActivated = isAccountActivated
        self.gasFees = gasFees
        self.gasUsed = gasUsed
        self.gasLimit = gasLimit
        self.gasCredit = gasCredit
        self.mode = mode
        self.exitCode = exitCode
        self.vmSteps = vmSteps
        self.vmInitStateHash = vmInitStateHash
        self.vmFinalStateHash = vmFinalStateHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSkipped
        case isSuccess
        case isMsgStateUsed
        case isAccountActivated
        case gasFees
        case gasUsed
        case gasLimit
        case gasCredit
        case mode
        case exitCode
        case vmSteps
        case vmInitStateHash
        case vmFinalStateHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isSkipped, forKey: .isSkipped)
        try container.encode(isSuccess, forKey: .isSuccess)
        try container.encode(isMsgStateUsed, forKey: .isMsgStateUsed)
        try container.encode(isAccountActivated, forKey: .isAccountActivated)
        try container.encode(gasFees, forKey: .gasFees)
        try container.encode(gasUsed, forKey: .gasUsed)
        try container.encode(gasLimit, forKey: .gasLimit)
        try container.encodeIfPresent(gasCredit, forKey: .gasCredit)
        try container.encode(mode, forKey: .mode)
        try container.encode(exitCode, forKey: .exitCode)
        try container.encode(vmSteps, forKey: .vmSteps)
        try container.encodeIfPresent(vmInitStateHash, forKey: .vmInitStateHash)
        try container.encodeIfPresent(vmFinalStateHash, forKey: .vmFinalStateHash)
    }
}




extension TONEmulationComputePhase: JSValueCodable {}

