//
//  TONGaslessSendResponse.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Response from a gasless send. Extends &#x60;SendTransactionResponse&#x60; (&#x60;boc&#x60;, &#x60;normalizedBoc&#x60;, &#x60;normalizedHash&#x60; of the broadcasted external-in message) with the signed internal-message BoC produced by &#x60;wallet.signMessage&#x60; for the relayer to wrap. */

public struct TONGaslessSendResponse: Codable {

    public var boc: TONBase64
    public var normalizedBoc: TONBase64
    public var normalizedHash: TONHex
    public var internalBoc: TONBase64

    public init(boc: TONBase64, normalizedBoc: TONBase64, normalizedHash: TONHex, internalBoc: TONBase64) {
        self.boc = boc
        self.normalizedBoc = normalizedBoc
        self.normalizedHash = normalizedHash
        self.internalBoc = internalBoc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case boc
        case normalizedBoc
        case normalizedHash
        case internalBoc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(boc, forKey: .boc)
        try container.encode(normalizedBoc, forKey: .normalizedBoc)
        try container.encode(normalizedHash, forKey: .normalizedHash)
        try container.encode(internalBoc, forKey: .internalBoc)
    }
}




extension TONGaslessSendResponse: JSValueCodable {}

