//
//  TONGaslessQuote.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Quote for a gasless transaction produced by &#x60;GaslessProvider.getQuote&#x60;.  Contains relayer-wrapped messages that should be passed to &#x60;wallet.signMessage&#x60; in place of the caller&#39;s original messages, together with the fee the relayer will deduct and the timestamp after which the bundle expires. */

public struct TONGaslessQuote: Codable {

    public var network: TONNetwork
    /** Relayer-wrapped messages ready to be signed */
    public var messages: [TONTransactionRequestMessage]
    public var fee: TONTokenAmount
    /** Unix timestamp after which the bundle becomes invalid for relay */
    public var validUntil: Double
    public var from: TONUserFriendlyAddress

    public init(network: TONNetwork, messages: [TONTransactionRequestMessage], fee: TONTokenAmount, validUntil: Double, from: TONUserFriendlyAddress) {
        self.network = network
        self.messages = messages
        self.fee = fee
        self.validUntil = validUntil
        self.from = from
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
        case messages
        case fee
        case validUntil
        case from
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(network, forKey: .network)
        try container.encode(messages, forKey: .messages)
        try container.encode(fee, forKey: .fee)
        try container.encode(validUntil, forKey: .validUntil)
        try container.encode(from, forKey: .from)
    }
}




extension TONGaslessQuote: JSValueCodable {}

