//
//  TONGaslessQuoteParams.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Parameters to quote a gasless transaction.  The relayer wraps the caller&#39;s messages with fee-collection logic and returns a new set of messages that the wallet should sign via &#x60;signMessage&#x60;. */

public struct TONGaslessQuoteParams: Codable {

    public var network: TONNetwork
    public var feeAsset: TONUserFriendlyAddress?
    public var walletAddress: TONUserFriendlyAddress
    public var walletPublicKey: TONHex
    /** Messages that the caller wants to include in the transaction */
    public var messages: [TONTransactionRequestMessage]

    public init(network: TONNetwork, feeAsset: TONUserFriendlyAddress? = nil, walletAddress: TONUserFriendlyAddress, walletPublicKey: TONHex, messages: [TONTransactionRequestMessage]) {
        self.network = network
        self.feeAsset = feeAsset
        self.walletAddress = walletAddress
        self.walletPublicKey = walletPublicKey
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
        case feeAsset
        case walletAddress
        case walletPublicKey
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(network, forKey: .network)
        try container.encodeIfPresent(feeAsset, forKey: .feeAsset)
        try container.encode(walletAddress, forKey: .walletAddress)
        try container.encode(walletPublicKey, forKey: .walletPublicKey)
        try container.encode(messages, forKey: .messages)
    }
}




extension TONGaslessQuoteParams: JSValueCodable {}

