//
//  TONGaslessConfig.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Provider-level configuration for a gasless relayer on a given network.  Bundles every piece of provider state a consumer needs to drive a gasless transfer end-to-end:  - &#x60;relayAddress&#x60; — where the relayer wants residual TON (e.g. jetton-transfer    &#x60;responseDestination&#x60;) returned to.  - &#x60;supportedAssets&#x60; — what the relayer accepts as fee payment. */

public struct TONGaslessConfig: Codable {

    public var relayAddress: TONUserFriendlyAddress
    /** Assets the relayer accepts as fee payment. */
    public var supportedAssets: [TONGaslessSupportedAsset]

    public init(relayAddress: TONUserFriendlyAddress, supportedAssets: [TONGaslessSupportedAsset]) {
        self.relayAddress = relayAddress
        self.supportedAssets = supportedAssets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relayAddress
        case supportedAssets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(relayAddress, forKey: .relayAddress)
        try container.encode(supportedAssets, forKey: .supportedAssets)
    }
}




extension TONGaslessConfig: JSValueCodable {}

