//
//  TONJettonsResponse.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Response containing a list of Jetton tokens. */

public struct TONJettonsResponse: Codable {

    /** Map of raw addresses to their metadata entries. */
    public var addressBook: [String: TONAddressBookEntry]
    /** List of Jettons */
    public var jettons: [TONJetton]

    public init(addressBook: [String: TONAddressBookEntry], jettons: [TONJetton]) {
        self.addressBook = addressBook
        self.jettons = jettons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addressBook
        case jettons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addressBook, forKey: .addressBook)
        try container.encode(jettons, forKey: .jettons)
    }
}




extension TONJettonsResponse: JSValueCodable {}

