//
//  TONJettonTransferItem.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt


public struct TONJettonTransferItem: Codable {

    public var master: String
    public var destination: String
    public var amount: String
    public var attachAmount: String?
    public var queryId: String?
    public var responseDestination: String?
    public var customPayload: TONBase64?
    public var forwardAmount: String?
    public var forwardPayload: TONBase64?
    public let type: String

    public init(master: String, destination: String, amount: String, attachAmount: String? = nil, queryId: String? = nil, responseDestination: String? = nil, customPayload: TONBase64? = nil, forwardAmount: String? = nil, forwardPayload: TONBase64? = nil) {
        self.type = "jetton"
        self.master = master
        self.destination = destination
        self.amount = amount
        self.attachAmount = attachAmount
        self.queryId = queryId
        self.responseDestination = responseDestination
        self.customPayload = customPayload
        self.forwardAmount = forwardAmount
        self.forwardPayload = forwardPayload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case master
        case destination
        case amount
        case attachAmount
        case queryId
        case responseDestination
        case customPayload
        case forwardAmount
        case forwardPayload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(master, forKey: .master)
        try container.encode(destination, forKey: .destination)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(attachAmount, forKey: .attachAmount)
        try container.encodeIfPresent(queryId, forKey: .queryId)
        try container.encodeIfPresent(responseDestination, forKey: .responseDestination)
        try container.encodeIfPresent(customPayload, forKey: .customPayload)
        try container.encodeIfPresent(forwardAmount, forKey: .forwardAmount)
        try container.encodeIfPresent(forwardPayload, forKey: .forwardPayload)
    }
}




extension TONJettonTransferItem: JSValueCodable {}

