//
//  TONJettonVerification.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Verification status of a Jetton. */

public struct TONJettonVerification: Codable {

    public enum Source: String, Codable, CaseIterable {
        case toncenter = "toncenter"
        case community = "community"
        case manual = "manual"
    }    /** Indicates whether the jetton has been verified */
    public var verified: Bool
    /** Source of the verification */
    public var source: Source?
    /** Warnings associated with the jetton */
    public var warnings: [String]?

    public init(verified: Bool, source: Source? = nil, warnings: [String]? = nil) {
        self.verified = verified
        self.source = source
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verified
        case source
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verified, forKey: .verified)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(warnings, forKey: .warnings)
    }
}




extension TONJettonVerification: JSValueCodable {}

