//
//  TONJettonInfo.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Detailed information about a Jetton master contract. */

public struct TONJettonInfo: Codable {

    /** The Jetton master contract address */
    public var address: String
    /** The token name */
    public var name: String
    /** The token symbol */
    public var symbol: String
    /** The token description */
    public var description: String
    /** The number of decimal places used by the token */
    public var decimals: Int?
    /** Total supply in the token's smallest units */
    public var totalSupply: BigInt?
    /** URL of the token image */
    public var image: String?
    /** Inline base64-encoded image data */
    public var imageData: String?
    /** URI pointing to the token metadata */
    public var uri: String?
    public var verification: TONJettonVerification?
    /** Additional arbitrary metadata related to the jetton */
    public var metadata: [String: AnyCodable]?

    public init(address: String, name: String, symbol: String, description: String, decimals: Int? = nil, totalSupply: BigInt? = nil, image: String? = nil, imageData: String? = nil, uri: String? = nil, verification: TONJettonVerification? = nil, metadata: [String: AnyCodable]? = nil) {
        self.address = address
        self.name = name
        self.symbol = symbol
        self.description = description
        self.decimals = decimals
        self.totalSupply = totalSupply
        self.image = image
        self.imageData = imageData
        self.uri = uri
        self.verification = verification
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case name
        case symbol
        case description
        case decimals
        case totalSupply
        case image
        case imageData = "image_data"
        case uri
        case verification
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(name, forKey: .name)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(description, forKey: .description)
        try container.encodeIfPresent(decimals, forKey: .decimals)
        try container.encodeIfPresent(totalSupply, forKey: .totalSupply)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(imageData, forKey: .imageData)
        try container.encodeIfPresent(uri, forKey: .uri)
        try container.encodeIfPresent(verification, forKey: .verification)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}




extension TONJettonInfo: JSValueCodable {}

