//
//  TONMasterchainInfo.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Information about the latest masterchain block. */

public struct TONMasterchainInfo: Codable {

    /** Sequence number of the masterchain block */
    public var seqno: Int
    /** Shard identifier of the block */
    public var shard: String
    /** Workchain ID of the block */
    public var workchain: Int
    public var fileHash: TONHex
    public var rootHash: TONHex

    public init(seqno: Int, shard: String, workchain: Int, fileHash: TONHex, rootHash: TONHex) {
        self.seqno = seqno
        self.shard = shard
        self.workchain = workchain
        self.fileHash = fileHash
        self.rootHash = rootHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seqno
        case shard
        case workchain
        case fileHash
        case rootHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(seqno, forKey: .seqno)
        try container.encode(shard, forKey: .shard)
        try container.encode(workchain, forKey: .workchain)
        try container.encode(fileHash, forKey: .fileHash)
        try container.encode(rootHash, forKey: .rootHash)
    }
}




extension TONMasterchainInfo: JSValueCodable {}

