//
//  TONNFTTransferRequest.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Request parameters for transferring an NFT to another address. */

public struct TONNFTTransferRequest: Codable {

    public var nftAddress: TONUserFriendlyAddress
    public var transferAmount: TONTokenAmount?
    public var recipientAddress: TONUserFriendlyAddress
    /** Human-readable comment attached to the transfer */
    public var comment: String?

    public init(nftAddress: TONUserFriendlyAddress, transferAmount: TONTokenAmount? = nil, recipientAddress: TONUserFriendlyAddress, comment: String? = nil) {
        self.nftAddress = nftAddress
        self.transferAmount = transferAmount
        self.recipientAddress = recipientAddress
        self.comment = comment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nftAddress
        case transferAmount
        case recipientAddress
        case comment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nftAddress, forKey: .nftAddress)
        try container.encodeIfPresent(transferAmount, forKey: .transferAmount)
        try container.encode(recipientAddress, forKey: .recipientAddress)
        try container.encodeIfPresent(comment, forKey: .comment)
    }
}




extension TONNFTTransferRequest: JSValueCodable {}

