//
//  TONNFTAttribute.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Attribute/trait of an NFT, commonly used for rarity and properties. */

public struct TONNFTAttribute: Codable {

    /** Category or type of the trait (e.g., \"Background\", \"Eyes\") */
    public var traitType: String?
    /** How the attribute should be displayed (e.g., \"string\", \"number\", \"date\") */
    public var displayType: String?
    /** Value of the attribute (e.g., \"Blue\", \"Rare\") */
    public var value: String?

    public init(traitType: String? = nil, displayType: String? = nil, value: String? = nil) {
        self.traitType = traitType
        self.displayType = displayType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case traitType
        case displayType
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(traitType, forKey: .traitType)
        try container.encodeIfPresent(displayType, forKey: .displayType)
        try container.encodeIfPresent(value, forKey: .value)
    }
}




extension TONNFTAttribute: JSValueCodable {}

