//
//  TONNFTCollection.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** NFT collection on the TON blockchain (TEP-62 standard). */

public struct TONNFTCollection: Codable {

    public var address: TONUserFriendlyAddress
    /** The name of the NFT collection */
    public var name: String?
    public var image: TONTokenImage?
    /** A brief description of the NFT collection */
    public var description: String?
    /** The index value for the next item to be minted in the collection */
    public var nextItemIndex: String?
    public var codeHash: TONHex?
    public var dataHash: TONHex?
    public var ownerAddress: TONUserFriendlyAddress?
    /** Additional arbitrary data related to the NFT collection */
    public var extra: [String: AnyCodable]?

    public init(address: TONUserFriendlyAddress, name: String? = nil, image: TONTokenImage? = nil, description: String? = nil, nextItemIndex: String? = nil, codeHash: TONHex? = nil, dataHash: TONHex? = nil, ownerAddress: TONUserFriendlyAddress? = nil, extra: [String: AnyCodable]? = nil) {
        self.address = address
        self.name = name
        self.image = image
        self.description = description
        self.nextItemIndex = nextItemIndex
        self.codeHash = codeHash
        self.dataHash = dataHash
        self.ownerAddress = ownerAddress
        self.extra = extra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case name
        case image
        case description
        case nextItemIndex
        case codeHash
        case dataHash
        case ownerAddress
        case extra
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(nextItemIndex, forKey: .nextItemIndex)
        try container.encodeIfPresent(codeHash, forKey: .codeHash)
        try container.encodeIfPresent(dataHash, forKey: .dataHash)
        try container.encodeIfPresent(ownerAddress, forKey: .ownerAddress)
        try container.encodeIfPresent(extra, forKey: .extra)
    }
}




extension TONNFTCollection: JSValueCodable {}

