//
//  TONNFT.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Non-fungible token (NFT) on the TON blockchain. */

public struct TONNFT: Codable {

    public var address: TONUserFriendlyAddress
    /** Index of the item within its collection */
    public var index: String?
    public var info: TONTokenInfo?
    /** Custom attributes/traits of the NFT (e.g., rarity, properties) */
    public var attributes: [TONNFTAttribute]?
    public var collection: TONNFTCollection?
    public var auctionContractAddress: TONUserFriendlyAddress?
    public var codeHash: TONHex?
    public var dataHash: TONHex?
    /** Whether the NFT contract has been initialized */
    public var isInited: Bool?
    /** Whether the NFT is soulbound (non-transferable) */
    public var isSoulbound: Bool?
    /** Whether the NFT is currently listed for sale */
    public var isOnSale: Bool?
    public var ownerAddress: TONUserFriendlyAddress?
    public var realOwnerAddress: TONUserFriendlyAddress?
    public var saleContractAddress: TONUserFriendlyAddress?
    /** Off-chain metadata of the NFT (key-value pairs) */
    public var extra: [String: AnyCodable]?

    public init(address: TONUserFriendlyAddress, index: String? = nil, info: TONTokenInfo? = nil, attributes: [TONNFTAttribute]? = nil, collection: TONNFTCollection? = nil, auctionContractAddress: TONUserFriendlyAddress? = nil, codeHash: TONHex? = nil, dataHash: TONHex? = nil, isInited: Bool? = nil, isSoulbound: Bool? = nil, isOnSale: Bool? = nil, ownerAddress: TONUserFriendlyAddress? = nil, realOwnerAddress: TONUserFriendlyAddress? = nil, saleContractAddress: TONUserFriendlyAddress? = nil, extra: [String: AnyCodable]? = nil) {
        self.address = address
        self.index = index
        self.info = info
        self.attributes = attributes
        self.collection = collection
        self.auctionContractAddress = auctionContractAddress
        self.codeHash = codeHash
        self.dataHash = dataHash
        self.isInited = isInited
        self.isSoulbound = isSoulbound
        self.isOnSale = isOnSale
        self.ownerAddress = ownerAddress
        self.realOwnerAddress = realOwnerAddress
        self.saleContractAddress = saleContractAddress
        self.extra = extra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case index
        case info
        case attributes
        case collection
        case auctionContractAddress
        case codeHash
        case dataHash
        case isInited
        case isSoulbound
        case isOnSale
        case ownerAddress
        case realOwnerAddress
        case saleContractAddress
        case extra
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encodeIfPresent(info, forKey: .info)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(collection, forKey: .collection)
        try container.encodeIfPresent(auctionContractAddress, forKey: .auctionContractAddress)
        try container.encodeIfPresent(codeHash, forKey: .codeHash)
        try container.encodeIfPresent(dataHash, forKey: .dataHash)
        try container.encodeIfPresent(isInited, forKey: .isInited)
        try container.encodeIfPresent(isSoulbound, forKey: .isSoulbound)
        try container.encodeIfPresent(isOnSale, forKey: .isOnSale)
        try container.encodeIfPresent(ownerAddress, forKey: .ownerAddress)
        try container.encodeIfPresent(realOwnerAddress, forKey: .realOwnerAddress)
        try container.encodeIfPresent(saleContractAddress, forKey: .saleContractAddress)
        try container.encodeIfPresent(extra, forKey: .extra)
    }
}




extension TONNFT: JSValueCodable {}

