//
//  TONOmnistonProviderOptions.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Provider-specific options for Omniston swap operations */

public struct TONOmnistonProviderOptions: Codable {

    /** The address of the referrer */
    public var referrerAddress: String?
    /** Referrer fee in basis points (1 bp = 0.01%) */
    public var referrerFeeBps: Int?
    /** Whether a flexible referrer fee is allowed */
    public var flexibleReferrerFee: Bool?
    /** Settlement methods to use for the swap */
    public var settlementMethods: [TONSettlementMethod]?

    public init(referrerAddress: String? = nil, referrerFeeBps: Int? = nil, flexibleReferrerFee: Bool? = nil, settlementMethods: [TONSettlementMethod]? = nil) {
        self.referrerAddress = referrerAddress
        self.referrerFeeBps = referrerFeeBps
        self.flexibleReferrerFee = flexibleReferrerFee
        self.settlementMethods = settlementMethods
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referrerAddress
        case referrerFeeBps
        case flexibleReferrerFee
        case settlementMethods
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(referrerAddress, forKey: .referrerAddress)
        try container.encodeIfPresent(referrerFeeBps, forKey: .referrerFeeBps)
        try container.encodeIfPresent(flexibleReferrerFee, forKey: .flexibleReferrerFee)
        try container.encodeIfPresent(settlementMethods, forKey: .settlementMethods)
    }
}




extension TONOmnistonProviderOptions: JSValueCodable {}

