//
//  TONOmnistonSwapProviderConfig.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Configuration for the Omniston Swap Provider */

public struct TONOmnistonSwapProviderConfig: Codable {

    /** The address of the referrer */
    public var referrerAddress: String?
    /** Referrer fee in basis points (1 bp = 0.01%) */
    public var referrerFeeBps: Int?
    /** Whether a flexible referrer fee is allowed */
    public var flexibleReferrerFee: Bool?
    /** Optional URL for the Omniston API */
    public var apiUrl: URL?
    /** Default slippage tolerance in basis points (1 bp = 0.01%) */
    public var defaultSlippageBps: Int?
    /** Timeout for quote requests in milliseconds */
    public var quoteTimeoutMs: Int?
    /** Timeout for build-transaction requests in milliseconds. Guards against indefinite hangs when network connectivity is lost between getting a quote and signing — `buildTransfer` would otherwise wait without surfacing an error. */
    public var buildTimeoutMs: Int?
    /** Identifier for the provider */
    public var providerId: String?
    public var metadata: TONSwapProviderMetadataOverride?

    public init(referrerAddress: String? = nil, referrerFeeBps: Int? = nil, flexibleReferrerFee: Bool? = nil, apiUrl: URL? = nil, defaultSlippageBps: Int? = nil, quoteTimeoutMs: Int? = nil, buildTimeoutMs: Int? = nil, providerId: String? = nil, metadata: TONSwapProviderMetadataOverride? = nil) {
        self.referrerAddress = referrerAddress
        self.referrerFeeBps = referrerFeeBps
        self.flexibleReferrerFee = flexibleReferrerFee
        self.apiUrl = apiUrl
        self.defaultSlippageBps = defaultSlippageBps
        self.quoteTimeoutMs = quoteTimeoutMs
        self.buildTimeoutMs = buildTimeoutMs
        self.providerId = providerId
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referrerAddress
        case referrerFeeBps
        case flexibleReferrerFee
        case apiUrl
        case defaultSlippageBps
        case quoteTimeoutMs
        case buildTimeoutMs
        case providerId
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(referrerAddress, forKey: .referrerAddress)
        try container.encodeIfPresent(referrerFeeBps, forKey: .referrerFeeBps)
        try container.encodeIfPresent(flexibleReferrerFee, forKey: .flexibleReferrerFee)
        try container.encodeIfPresent(apiUrl, forKey: .apiUrl)
        try container.encodeIfPresent(defaultSlippageBps, forKey: .defaultSlippageBps)
        try container.encodeIfPresent(quoteTimeoutMs, forKey: .quoteTimeoutMs)
        try container.encodeIfPresent(buildTimeoutMs, forKey: .buildTimeoutMs)
        try container.encodeIfPresent(providerId, forKey: .providerId)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}




extension TONOmnistonSwapProviderConfig: JSValueCodable {}

