//
//  TONPreparedSignData.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Prepared sign data ready for signing by the wallet. */

public struct TONPreparedSignData: Codable {

    public var address: TONUserFriendlyAddress
    /** Unix timestamp when the sign request was created */
    public var timestamp: Double
    /** Domain requesting the signature (e.g., \"example.com\") */
    public var domain: String
    public var payload: TONSignDataPayload
    public var hash: TONHex

    public init(address: TONUserFriendlyAddress, timestamp: Double, domain: String, payload: TONSignDataPayload, hash: TONHex) {
        self.address = address
        self.timestamp = timestamp
        self.domain = domain
        self.payload = payload
        self.hash = hash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case timestamp
        case domain
        case payload
        case hash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(domain, forKey: .domain)
        try container.encode(payload, forKey: .payload)
        try container.encode(hash, forKey: .hash)
    }
}




extension TONPreparedSignData: JSValueCodable {}

