//
//  TONProofMessage.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Message structure used for TON Connect proof of ownership. */

public struct TONProofMessage: Codable {

    /** Workchain ID of the wallet address */
    public var workchain: Int
    public var addressHash: TONHex
    /** Unix timestamp when the proof was created */
    public var timestamp: Int
    public var domain: TONProofMessageDomain
    /** Payload string to be signed */
    public var payload: String
    public var stateInit: TONBase64
    public var signature: TONHex?

    public init(workchain: Int, addressHash: TONHex, timestamp: Int, domain: TONProofMessageDomain, payload: String, stateInit: TONBase64, signature: TONHex? = nil) {
        self.workchain = workchain
        self.addressHash = addressHash
        self.timestamp = timestamp
        self.domain = domain
        self.payload = payload
        self.stateInit = stateInit
        self.signature = signature
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workchain
        case addressHash
        case timestamp
        case domain
        case payload
        case stateInit
        case signature
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workchain, forKey: .workchain)
        try container.encode(addressHash, forKey: .addressHash)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(domain, forKey: .domain)
        try container.encode(payload, forKey: .payload)
        try container.encode(stateInit, forKey: .stateInit)
        try container.encodeIfPresent(signature, forKey: .signature)
    }
}




extension TONProofMessage: JSValueCodable {}

