//
//  TONRawStackItem.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public enum TONRawStackItem: Codable {

    case num(String)
    case cell(String)
    case slice(String)
    case builder(String)
    case tuple([TONRawStackItem])
    case list([TONRawStackItem])
    case null

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)
        switch type {

        case "num":
            let value = try container.decode(String.self, forKey: .value)
            self = .num(value)
        case "cell":
            let value = try container.decode(String.self, forKey: .value)
            self = .cell(value)
        case "slice":
            let value = try container.decode(String.self, forKey: .value)
            self = .slice(value)
        case "builder":
            let value = try container.decode(String.self, forKey: .value)
            self = .builder(value)
        case "tuple":
            let value = try container.decode([TONRawStackItem].self, forKey: .value)
            self = .tuple(value)
        case "list":
            let value = try container.decode([TONRawStackItem].self, forKey: .value)
            self = .list(value)
        case "null":
            self = .null
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown type: \(type)"
            )
        }
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {

        case .num(let value):
            try container.encode("num", forKey: .type)
            try container.encode(value, forKey: .value)
        case .cell(let value):
            try container.encode("cell", forKey: .type)
            try container.encode(value, forKey: .value)
        case .slice(let value):
            try container.encode("slice", forKey: .type)
            try container.encode(value, forKey: .value)
        case .builder(let value):
            try container.encode("builder", forKey: .type)
            try container.encode(value, forKey: .value)
        case .tuple(let value):
            try container.encode("tuple", forKey: .type)
            try container.encode(value, forKey: .value)
        case .list(let value):
            try container.encode("list", forKey: .type)
            try container.encode(value, forKey: .value)
        case .null:
            try container.encode("null", forKey: .type)
        }
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }
}



extension TONRawStackItem: JSValueCodable {}

