//
//  TONSwapParams.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public struct TONSwapParams<TProviderOptions: Codable>: Codable {
    public var quote: TONSwapQuote
    public var userAddress: TONUserFriendlyAddress
    public var destinationAddress: TONUserFriendlyAddress?
    /** Slippage tolerance in basis points (1 bp = 0.01%) */
    public var slippageBps: Double?
    /** Transaction deadline in unix timestamp */
    public var deadline: Double?
    /** Provider-specific options */
    public var providerOptions: TProviderOptions?

    public init(quote: TONSwapQuote, userAddress: TONUserFriendlyAddress, destinationAddress: TONUserFriendlyAddress? = nil, slippageBps: Double? = nil, deadline: Double? = nil, providerOptions: TProviderOptions? = nil) {
        self.quote = quote
        self.userAddress = userAddress
        self.destinationAddress = destinationAddress
        self.slippageBps = slippageBps
        self.deadline = deadline
        self.providerOptions = providerOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case quote
        case userAddress
        case destinationAddress
        case slippageBps
        case deadline
        case providerOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(quote, forKey: .quote)
        try container.encode(userAddress, forKey: .userAddress)
        try container.encodeIfPresent(destinationAddress, forKey: .destinationAddress)
        try container.encodeIfPresent(slippageBps, forKey: .slippageBps)
        try container.encodeIfPresent(deadline, forKey: .deadline)
        try container.encodeIfPresent(providerOptions, forKey: .providerOptions)
    }
}



extension TONSwapParams: JSValueCodable {}

