//
//  TONSwapQuote.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Swap quote response with pricing information */

public struct TONSwapQuote: Codable {

    public var fromToken: TONSwapToken
    public var toToken: TONSwapToken
    public var rawFromAmount: TONTokenAmount
    public var rawToAmount: TONTokenAmount
    /** Amount of tokens to sell */
    public var fromAmount: String
    /** Amount of tokens to buy */
    public var toAmount: String
    public var rawMinReceived: TONTokenAmount
    /** Minimum amount of tokens to receive (after slippage) */
    public var minReceived: String
    public var network: TONNetwork
    /** Price impact of the swap in basis points (100 = 1%) */
    public var priceImpact: Int?
    /** Identifier of the swap provider */
    public var providerId: String
    /** Unix timestamp in seconds when the quote expires */
    public var expiresAt: Int?
    /** Provider-specific metadata for the quote */
    public var metadata: AnyCodable?

    public init(fromToken: TONSwapToken, toToken: TONSwapToken, rawFromAmount: TONTokenAmount, rawToAmount: TONTokenAmount, fromAmount: String, toAmount: String, rawMinReceived: TONTokenAmount, minReceived: String, network: TONNetwork, priceImpact: Int? = nil, providerId: String, expiresAt: Int? = nil, metadata: AnyCodable? = nil) {
        self.fromToken = fromToken
        self.toToken = toToken
        self.rawFromAmount = rawFromAmount
        self.rawToAmount = rawToAmount
        self.fromAmount = fromAmount
        self.toAmount = toAmount
        self.rawMinReceived = rawMinReceived
        self.minReceived = minReceived
        self.network = network
        self.priceImpact = priceImpact
        self.providerId = providerId
        self.expiresAt = expiresAt
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fromToken
        case toToken
        case rawFromAmount
        case rawToAmount
        case fromAmount
        case toAmount
        case rawMinReceived
        case minReceived
        case network
        case priceImpact
        case providerId
        case expiresAt
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fromToken, forKey: .fromToken)
        try container.encode(toToken, forKey: .toToken)
        try container.encode(rawFromAmount, forKey: .rawFromAmount)
        try container.encode(rawToAmount, forKey: .rawToAmount)
        try container.encode(fromAmount, forKey: .fromAmount)
        try container.encode(toAmount, forKey: .toAmount)
        try container.encode(rawMinReceived, forKey: .rawMinReceived)
        try container.encode(minReceived, forKey: .minReceived)
        try container.encode(network, forKey: .network)
        try container.encodeIfPresent(priceImpact, forKey: .priceImpact)
        try container.encode(providerId, forKey: .providerId)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}




extension TONSwapQuote: JSValueCodable {}

