//
//  TONStreamingEvents.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import BigInt


public struct TONStreamingEvents: Codable {

    public var streamingbalanceUpdate: TONBalanceUpdate
    public var streamingtransactions: TONTransactionsUpdate
    public var streamingjettonsUpdate: TONJettonUpdate

    public init(streamingbalanceUpdate: TONBalanceUpdate, streamingtransactions: TONTransactionsUpdate, streamingjettonsUpdate: TONJettonUpdate) {
        self.streamingbalanceUpdate = streamingbalanceUpdate
        self.streamingtransactions = streamingtransactions
        self.streamingjettonsUpdate = streamingjettonsUpdate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case streamingbalanceUpdate = "streaming:balance-update"
        case streamingtransactions = "streaming:transactions"
        case streamingjettonsUpdate = "streaming:jettons-update"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(streamingbalanceUpdate, forKey: .streamingbalanceUpdate)
        try container.encode(streamingtransactions, forKey: .streamingtransactions)
        try container.encode(streamingjettonsUpdate, forKey: .streamingjettonsUpdate)
    }
}




extension TONStreamingEvents: JSValueCodable {}

