//
//  TONStakingProviderMetadataOverride.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Used in provider configuration to override fields of the provider&#39;s metadata. */

public struct TONStakingProviderMetadataOverride: Codable {

    public var name: String?
    public var stakeToken: TONStakingTokenInfo?
    public var receiveToken: TONStakingTokenInfo?
    public var contractAddress: TONUserFriendlyAddress?
    public var supportedUnstakeModes: [TONUnstakeMode]?
    public var supportsReversedQuote: Bool?

    public init(name: String? = nil, stakeToken: TONStakingTokenInfo? = nil, receiveToken: TONStakingTokenInfo? = nil, contractAddress: TONUserFriendlyAddress? = nil, supportedUnstakeModes: [TONUnstakeMode]? = nil, supportsReversedQuote: Bool? = nil) {
        self.name = name
        self.stakeToken = stakeToken
        self.receiveToken = receiveToken
        self.contractAddress = contractAddress
        self.supportedUnstakeModes = supportedUnstakeModes
        self.supportsReversedQuote = supportsReversedQuote
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case stakeToken
        case receiveToken
        case contractAddress
        case supportedUnstakeModes
        case supportsReversedQuote
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(stakeToken, forKey: .stakeToken)
        try container.encodeIfPresent(receiveToken, forKey: .receiveToken)
        try container.encodeIfPresent(contractAddress, forKey: .contractAddress)
        try container.encodeIfPresent(supportedUnstakeModes, forKey: .supportedUnstakeModes)
        try container.encodeIfPresent(supportsReversedQuote, forKey: .supportsReversedQuote)
    }
}




extension TONStakingProviderMetadataOverride: JSValueCodable {}

