//
//  TONSwapToken.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Token type for swap */

public struct TONSwapToken: Codable {

    public var address: String
    public var decimals: Double
    public var name: String?
    public var symbol: String?
    public var image: String?
    public var chainId: String?

    public init(address: String, decimals: Double, name: String? = nil, symbol: String? = nil, image: String? = nil, chainId: String? = nil) {
        self.address = address
        self.decimals = decimals
        self.name = name
        self.symbol = symbol
        self.image = image
        self.chainId = chainId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case decimals
        case name
        case symbol
        case image
        case chainId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(decimals, forKey: .decimals)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(symbol, forKey: .symbol)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(chainId, forKey: .chainId)
    }
}




extension TONSwapToken: JSValueCodable {}

