//
//  TONStakingQuoteParams.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public struct TONStakingQuoteParams<TProviderOptions: Codable>: Codable {
    public var direction: TONStakingQuoteDirection
    /** Amount of tokens to stake or unstake */
    public var amount: String
    public var userAddress: TONUserFriendlyAddress?
    public var network: TONNetwork?
    public var unstakeMode: TONUnstakeMode?
    /** If true, for unstake requests the amount is specified in the staking coin (e.g. TON) instead of the Liquid Staking Token (e.g. tsTON). */
    public var isReversed: Bool?
    /** Provider-specific options */
    public var providerOptions: TProviderOptions?

    public init(direction: TONStakingQuoteDirection, amount: String, userAddress: TONUserFriendlyAddress? = nil, network: TONNetwork? = nil, unstakeMode: TONUnstakeMode? = nil, isReversed: Bool? = nil, providerOptions: TProviderOptions? = nil) {
        self.direction = direction
        self.amount = amount
        self.userAddress = userAddress
        self.network = network
        self.unstakeMode = unstakeMode
        self.isReversed = isReversed
        self.providerOptions = providerOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case direction
        case amount
        case userAddress
        case network
        case unstakeMode
        case isReversed
        case providerOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(direction, forKey: .direction)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(userAddress, forKey: .userAddress)
        try container.encodeIfPresent(network, forKey: .network)
        try container.encodeIfPresent(unstakeMode, forKey: .unstakeMode)
        try container.encodeIfPresent(isReversed, forKey: .isReversed)
        try container.encodeIfPresent(providerOptions, forKey: .providerOptions)
    }
}



extension TONStakingQuoteParams: JSValueCodable {}

