//
//  TONStakingProviderMetadata.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Static metadata for a staking provider */

public struct TONStakingProviderMetadata: Codable {

    /** Human-readable provider name (e.g. \"Tonstakers\") */
    public var name: String
    /** Supported unstake modes for this provider */
    public var supportedUnstakeModes: [TONUnstakeMode]
    /** Whether provider supports reversed quote format (e.g., passing TON instead of tsTON for unstake) */
    public var supportsReversedQuote: Bool
    public var stakeToken: TONStakingTokenInfo
    public var receiveToken: TONStakingTokenInfo?
    public var contractAddress: TONUserFriendlyAddress?

    public init(name: String, supportedUnstakeModes: [TONUnstakeMode], supportsReversedQuote: Bool, stakeToken: TONStakingTokenInfo, receiveToken: TONStakingTokenInfo? = nil, contractAddress: TONUserFriendlyAddress? = nil) {
        self.name = name
        self.supportedUnstakeModes = supportedUnstakeModes
        self.supportsReversedQuote = supportsReversedQuote
        self.stakeToken = stakeToken
        self.receiveToken = receiveToken
        self.contractAddress = contractAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case supportedUnstakeModes
        case supportsReversedQuote
        case stakeToken
        case receiveToken
        case contractAddress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(supportedUnstakeModes, forKey: .supportedUnstakeModes)
        try container.encode(supportsReversedQuote, forKey: .supportsReversedQuote)
        try container.encode(stakeToken, forKey: .stakeToken)
        try container.encodeIfPresent(receiveToken, forKey: .receiveToken)
        try container.encodeIfPresent(contractAddress, forKey: .contractAddress)
    }
}




extension TONStakingProviderMetadata: JSValueCodable {}

