//
//  TONStakingQuote.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Staking quote response with pricing information */

public struct TONStakingQuote: Codable {

    public var direction: TONStakingQuoteDirection
    public var rawAmountIn: TONTokenAmount
    public var rawAmountOut: TONTokenAmount
    /** Formatted amount of tokens being provided */
    public var amountIn: String
    /** Formatted estimated amount of tokens to be received */
    public var amountOut: String
    public var network: TONNetwork
    /** Identifier of the staking provider */
    public var providerId: String
    /** Annual Percentage Yield in basis points (100 = 1%) */
    public var apy: Double?
    public var unstakeMode: TONUnstakeMode?
    /** Provider-specific metadata for the quote */
    public var metadata: AnyCodable?

    public init(direction: TONStakingQuoteDirection, rawAmountIn: TONTokenAmount, rawAmountOut: TONTokenAmount, amountIn: String, amountOut: String, network: TONNetwork, providerId: String, apy: Double? = nil, unstakeMode: TONUnstakeMode? = nil, metadata: AnyCodable? = nil) {
        self.direction = direction
        self.rawAmountIn = rawAmountIn
        self.rawAmountOut = rawAmountOut
        self.amountIn = amountIn
        self.amountOut = amountOut
        self.network = network
        self.providerId = providerId
        self.apy = apy
        self.unstakeMode = unstakeMode
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case direction
        case rawAmountIn
        case rawAmountOut
        case amountIn
        case amountOut
        case network
        case providerId
        case apy
        case unstakeMode
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(direction, forKey: .direction)
        try container.encode(rawAmountIn, forKey: .rawAmountIn)
        try container.encode(rawAmountOut, forKey: .rawAmountOut)
        try container.encode(amountIn, forKey: .amountIn)
        try container.encode(amountOut, forKey: .amountOut)
        try container.encode(network, forKey: .network)
        try container.encode(providerId, forKey: .providerId)
        try container.encodeIfPresent(apy, forKey: .apy)
        try container.encodeIfPresent(unstakeMode, forKey: .unstakeMode)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}




extension TONStakingQuote: JSValueCodable {}

