//
//  TONSignDataRequestEvent.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Event containing a sign data request from a dApp via TON Connect. */

public struct TONSignDataRequestEvent: Codable {

    /** Unique identifier for the bridge event */
    public var id: String
    public var from: String?
    public var walletAddress: TONUserFriendlyAddress?
    /** Wallet identifier associated with the event */
    public var walletId: String?
    /** Domain of the dApp that initiated the event */
    public var domain: String?
    /** Whether the event originated from JS Bridge (injected provider) */
    public var isJsBridge: Bool?
    /** Browser tab ID for JS Bridge events */
    public var tabId: String?
    /** Session identifier for the connection */
    public var sessionId: String?
    public var isLocal: Bool?
    public var messageId: String?
    public var traceId: String?
    public var dAppInfo: TONDAppInfo?
    /** Raw TonConnect return strategy string. */
    public var returnStrategy: String?
    public var payload: TONSignDataPayload
    public var preview: TONSignDataRequestEventPreview

    public init(id: String, from: String? = nil, walletAddress: TONUserFriendlyAddress? = nil, walletId: String? = nil, domain: String? = nil, isJsBridge: Bool? = nil, tabId: String? = nil, sessionId: String? = nil, isLocal: Bool? = nil, messageId: String? = nil, traceId: String? = nil, dAppInfo: TONDAppInfo? = nil, returnStrategy: String? = nil, payload: TONSignDataPayload, preview: TONSignDataRequestEventPreview) {
        self.id = id
        self.from = from
        self.walletAddress = walletAddress
        self.walletId = walletId
        self.domain = domain
        self.isJsBridge = isJsBridge
        self.tabId = tabId
        self.sessionId = sessionId
        self.isLocal = isLocal
        self.messageId = messageId
        self.traceId = traceId
        self.dAppInfo = dAppInfo
        self.returnStrategy = returnStrategy
        self.payload = payload
        self.preview = preview
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case from
        case walletAddress
        case walletId
        case domain
        case isJsBridge
        case tabId
        case sessionId
        case isLocal
        case messageId
        case traceId
        case dAppInfo
        case returnStrategy
        case payload
        case preview
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(walletAddress, forKey: .walletAddress)
        try container.encodeIfPresent(walletId, forKey: .walletId)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(isJsBridge, forKey: .isJsBridge)
        try container.encodeIfPresent(tabId, forKey: .tabId)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(isLocal, forKey: .isLocal)
        try container.encodeIfPresent(messageId, forKey: .messageId)
        try container.encodeIfPresent(traceId, forKey: .traceId)
        try container.encodeIfPresent(dAppInfo, forKey: .dAppInfo)
        try container.encodeIfPresent(returnStrategy, forKey: .returnStrategy)
        try container.encode(payload, forKey: .payload)
        try container.encode(preview, forKey: .preview)
    }
}




extension TONSignDataRequestEvent: JSValueCodable {}

