//
//  TONStakingProviderInfo.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Dynamic staking information for a provider */

public struct TONStakingProviderInfo: Codable {

    /** Annual Percentage Yield in basis points (100 = 1%) */
    public var apy: Double
    public var rawInstantUnstakeAvailable: TONTokenAmount?
    /** Amount available for instant unstake */
    public var instantUnstakeAvailable: String?
    /** Exchange rate between stakeToken and receiveToken (e.g. 1 GRAM = 0.95 tsTON). Undefined when there is no receiveToken (direct/custodial staking). */
    public var exchangeRate: String?

    public init(apy: Double, rawInstantUnstakeAvailable: TONTokenAmount? = nil, instantUnstakeAvailable: String? = nil, exchangeRate: String? = nil) {
        self.apy = apy
        self.rawInstantUnstakeAvailable = rawInstantUnstakeAvailable
        self.instantUnstakeAvailable = instantUnstakeAvailable
        self.exchangeRate = exchangeRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apy
        case rawInstantUnstakeAvailable
        case instantUnstakeAvailable
        case exchangeRate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(apy, forKey: .apy)
        try container.encodeIfPresent(rawInstantUnstakeAvailable, forKey: .rawInstantUnstakeAvailable)
        try container.encodeIfPresent(instantUnstakeAvailable, forKey: .instantUnstakeAvailable)
        try container.encodeIfPresent(exchangeRate, forKey: .exchangeRate)
    }
}




extension TONStakingProviderInfo: JSValueCodable {}

