//
//  TONSignDataPreview.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public enum TONSignDataPreview: Codable {

    case text(TONSignDataPreviewText)
    case binary(TONSignDataPreviewBinary)
    case cell(TONSignDataPreviewCell)

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)
        switch type {

        case "text":
            let value = try container.decode(TONSignDataPreviewText.self, forKey: .value)
            self = .text(value)
        case "binary":
            let value = try container.decode(TONSignDataPreviewBinary.self, forKey: .value)
            self = .binary(value)
        case "cell":
            let value = try container.decode(TONSignDataPreviewCell.self, forKey: .value)
            self = .cell(value)
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown type: \(type)"
            )
        }
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {

        case .text(let value):
            try container.encode("text", forKey: .type)
            try container.encode(value, forKey: .value)
        case .binary(let value):
            try container.encode("binary", forKey: .type)
            try container.encode(value, forKey: .value)
        case .cell(let value):
            try container.encode("cell", forKey: .type)
            try container.encode(value, forKey: .value)
        }
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }
}



extension TONSignDataPreview: JSValueCodable {}

