//
//  TONTransactionTraceActionJettonSwapDetails.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Details of a Jetton swap action on a DEX. */

public struct TONTransactionTraceActionJettonSwapDetails: Codable {

    /** Name of the decentralized exchange */
    public var dex: String
    public var sender: TONUserFriendlyAddress?
    public var dexIncomingTransfer: TONTransactionTraceActionJettonTransfer?
    public var dexOutgoingTransfer: TONTransactionTraceActionJettonTransfer?
    /** Related peer swap operations (for multi-hop swaps) */
    public var peerSwaps: [AnyCodable]

    public init(dex: String, sender: TONUserFriendlyAddress? = nil, dexIncomingTransfer: TONTransactionTraceActionJettonTransfer? = nil, dexOutgoingTransfer: TONTransactionTraceActionJettonTransfer? = nil, peerSwaps: [AnyCodable]) {
        self.dex = dex
        self.sender = sender
        self.dexIncomingTransfer = dexIncomingTransfer
        self.dexOutgoingTransfer = dexOutgoingTransfer
        self.peerSwaps = peerSwaps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dex
        case sender
        case dexIncomingTransfer
        case dexOutgoingTransfer
        case peerSwaps
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dex, forKey: .dex)
        try container.encodeIfPresent(sender, forKey: .sender)
        try container.encodeIfPresent(dexIncomingTransfer, forKey: .dexIncomingTransfer)
        try container.encodeIfPresent(dexOutgoingTransfer, forKey: .dexOutgoingTransfer)
        try container.encode(peerSwaps, forKey: .peerSwaps)
    }
}




extension TONTransactionTraceActionJettonSwapDetails: JSValueCodable {}

