//
//  TONTransactionRequestMessage.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Individual message within a transaction request. */

public struct TONTransactionRequestMessage: Codable {

    /** Recipient wallet address in format received from caller (raw, user friendly) */
    public var address: String
    public var amount: TONTokenAmount
    public var mode: TONSendMode?
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var extraCurrency: [String: String]?
    public var stateInit: TONBase64?
    public var payload: TONBase64?

    public init(address: String, amount: TONTokenAmount, mode: TONSendMode? = nil, extraCurrency: [String: String]? = nil, stateInit: TONBase64? = nil, payload: TONBase64? = nil) {
        self.address = address
        self.amount = amount
        self.mode = mode
        self.extraCurrency = extraCurrency
        self.stateInit = stateInit
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case amount
        case mode
        case extraCurrency
        case stateInit
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(extraCurrency, forKey: .extraCurrency)
        try container.encodeIfPresent(stateInit, forKey: .stateInit)
        try container.encodeIfPresent(payload, forKey: .payload)
    }
}




extension TONTransactionRequestMessage: JSValueCodable {}

