//
//  TONTokenImage.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Token image URLs in various sizes for display purposes. */

public struct TONTokenImage: Codable {

    /** Original image URL */
    public var url: URL?
    /** Small thumbnail URL (typically 64x64 or similar) */
    public var smallUrl: URL?
    /** Medium-sized image URL (typically 256x256 or similar) */
    public var mediumUrl: URL?
    /** Large image URL (typically 512x512 or higher) */
    public var largeUrl: URL?
    /** Raw image data encoded in Base64 */
    public var data: Data?

    public init(url: URL? = nil, smallUrl: URL? = nil, mediumUrl: URL? = nil, largeUrl: URL? = nil, data: Data? = nil) {
        self.url = url
        self.smallUrl = smallUrl
        self.mediumUrl = mediumUrl
        self.largeUrl = largeUrl
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case smallUrl
        case mediumUrl
        case largeUrl
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(smallUrl, forKey: .smallUrl)
        try container.encodeIfPresent(mediumUrl, forKey: .mediumUrl)
        try container.encodeIfPresent(largeUrl, forKey: .largeUrl)
        try container.encodeIfPresent(data, forKey: .data)
    }
}




extension TONTokenImage: JSValueCodable {}

