//
//  TONTransactionTokenInfoJettonMasters.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Token information for Jetton master contracts. */

public struct TONTransactionTokenInfoJettonMasters: Codable {

    /** Indicates if the token contract is valid */
    public var isValid: Bool
    /** Type of token */
    public var type: String
    /** Additional metadata for the token, such as image sizes, decimal precision, external links, and marketplaces */
    public var extra: [String: AnyCodable]
    /** Display name of the Jetton */
    public var name: String
    /** Ticker symbol of the Jetton */
    public var symbol: String
    /** Human-readable description of the Jetton */
    public var description: String
    /** Number of decimal places for the Jetton amount */
    public var decimalsCount: Int
    public var image: TONTokenImage?
    /** Social media links for the Jetton project */
    public var social: [String]
    /** Metadata URI for the Jetton */
    public var uri: String
    /** Official website URLs for the Jetton project */
    public var websites: [String]

    public init(isValid: Bool, type: String, extra: [String: AnyCodable], name: String, symbol: String, description: String, decimalsCount: Int, image: TONTokenImage? = nil, social: [String], uri: String, websites: [String]) {
        self.isValid = isValid
        self.type = type
        self.extra = extra
        self.name = name
        self.symbol = symbol
        self.description = description
        self.decimalsCount = decimalsCount
        self.image = image
        self.social = social
        self.uri = uri
        self.websites = websites
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isValid
        case type
        case extra
        case name
        case symbol
        case description
        case decimalsCount
        case image
        case social
        case uri
        case websites
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isValid, forKey: .isValid)
        try container.encode(type, forKey: .type)
        try container.encode(extra, forKey: .extra)
        try container.encode(name, forKey: .name)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(description, forKey: .description)
        try container.encode(decimalsCount, forKey: .decimalsCount)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encode(social, forKey: .social)
        try container.encode(uri, forKey: .uri)
        try container.encode(websites, forKey: .websites)
    }
}




extension TONTransactionTokenInfoJettonMasters: JSValueCodable {}

