//
//  TONTonTransferItem.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt


public struct TONTonTransferItem: Codable {

    public var address: String
    public var amount: String
    public var payload: TONBase64?
    public var stateInit: TONBase64?
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var extraCurrency: [String: String]?
    public let type: String

    public init(address: String, amount: String, payload: TONBase64? = nil, stateInit: TONBase64? = nil, extraCurrency: [String: String]? = nil) {
        self.type = "ton"
        self.address = address
        self.amount = amount
        self.payload = payload
        self.stateInit = stateInit
        self.extraCurrency = extraCurrency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case address
        case amount
        case payload
        case stateInit
        case extraCurrency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(address, forKey: .address)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(payload, forKey: .payload)
        try container.encodeIfPresent(stateInit, forKey: .stateInit)
        try container.encodeIfPresent(extraCurrency, forKey: .extraCurrency)
    }
}




extension TONTonTransferItem: JSValueCodable {}

