//
//  TONTransactionStatusResponse.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt


public struct TONTransactionStatusResponse: Codable {

    public var status: TONTransactionStatus
    /** Total messages in the trace */
    public var totalMessages: Int
    /** Messages still pending */
    public var pendingMessages: Int
    /** Number of onchain messages (totalMessages - pendingMessages) */
    public var onchainMessages: Int

    public init(status: TONTransactionStatus, totalMessages: Int, pendingMessages: Int, onchainMessages: Int) {
        self.status = status
        self.totalMessages = totalMessages
        self.pendingMessages = pendingMessages
        self.onchainMessages = onchainMessages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case totalMessages
        case pendingMessages
        case onchainMessages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(totalMessages, forKey: .totalMessages)
        try container.encode(pendingMessages, forKey: .pendingMessages)
        try container.encode(onchainMessages, forKey: .onchainMessages)
    }
}




extension TONTransactionStatusResponse: JSValueCodable {}

