//
//  TONTransactionTraceMoneyFlowItem.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Individual token flow item. */

public struct TONTransactionTraceMoneyFlowItem: Codable {

    public var assetType: TONAssetType
    public var amount: TONTokenAmount
    public var tokenAddress: TONUserFriendlyAddress?
    public var fromAddress: TONUserFriendlyAddress?
    public var toAddress: TONUserFriendlyAddress?

    public init(assetType: TONAssetType, amount: TONTokenAmount, tokenAddress: TONUserFriendlyAddress? = nil, fromAddress: TONUserFriendlyAddress? = nil, toAddress: TONUserFriendlyAddress? = nil) {
        self.assetType = assetType
        self.amount = amount
        self.tokenAddress = tokenAddress
        self.fromAddress = fromAddress
        self.toAddress = toAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetType
        case amount
        case tokenAddress
        case fromAddress
        case toAddress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetType, forKey: .assetType)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(tokenAddress, forKey: .tokenAddress)
        try container.encodeIfPresent(fromAddress, forKey: .fromAddress)
        try container.encodeIfPresent(toAddress, forKey: .toAddress)
    }
}




extension TONTransactionTraceMoneyFlowItem: JSValueCodable {}

