//
//  TONTransactionTraceActionJettonTransfer.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt


public struct TONTransactionTraceActionJettonTransfer: Codable {

    public var asset: TONUserFriendlyAddress?
    public var source: TONUserFriendlyAddress?
    public var destination: TONUserFriendlyAddress?
    public var sourceJettonWallet: TONUserFriendlyAddress?
    public var destinationJettonWallet: TONUserFriendlyAddress?
    public var amount: TONTokenAmount?

    public init(asset: TONUserFriendlyAddress? = nil, source: TONUserFriendlyAddress? = nil, destination: TONUserFriendlyAddress? = nil, sourceJettonWallet: TONUserFriendlyAddress? = nil, destinationJettonWallet: TONUserFriendlyAddress? = nil, amount: TONTokenAmount? = nil) {
        self.asset = asset
        self.source = source
        self.destination = destination
        self.sourceJettonWallet = sourceJettonWallet
        self.destinationJettonWallet = destinationJettonWallet
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asset
        case source
        case destination
        case sourceJettonWallet
        case destinationJettonWallet
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(asset, forKey: .asset)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(destination, forKey: .destination)
        try container.encodeIfPresent(sourceJettonWallet, forKey: .sourceJettonWallet)
        try container.encodeIfPresent(destinationJettonWallet, forKey: .destinationJettonWallet)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}




extension TONTransactionTraceActionJettonTransfer: JSValueCodable {}

