//
//  TONTransactionTrace.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Trace of a transaction execution showing the full message chain. */

public struct TONTransactionTrace: Codable {

    /** Masterchain block sequence number where emulation was performed */
    public var mcBlockSeqno: Int
    public var trace: TONTransactionTraceNode
    /** Map of transaction hashes to transaction details */
    public var transactions: [String: TONTransaction]
    /** List of high-level actions extracted from the trace */
    public var actions: [TONTransactionTraceAction]
    public var randSeed: TONHex
    /** Whether the trace is incomplete due to limits or errors */
    public var isIncomplete: Bool

    public init(mcBlockSeqno: Int, trace: TONTransactionTraceNode, transactions: [String: TONTransaction], actions: [TONTransactionTraceAction], randSeed: TONHex, isIncomplete: Bool) {
        self.mcBlockSeqno = mcBlockSeqno
        self.trace = trace
        self.transactions = transactions
        self.actions = actions
        self.randSeed = randSeed
        self.isIncomplete = isIncomplete
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mcBlockSeqno
        case trace
        case transactions
        case actions
        case randSeed
        case isIncomplete
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mcBlockSeqno, forKey: .mcBlockSeqno)
        try container.encode(trace, forKey: .trace)
        try container.encode(transactions, forKey: .transactions)
        try container.encode(actions, forKey: .actions)
        try container.encode(randSeed, forKey: .randSeed)
        try container.encode(isIncomplete, forKey: .isIncomplete)
    }
}




extension TONTransactionTrace: JSValueCodable {}

