//
//  TONTonApiGaslessProviderConfig.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Configuration for &#x60;TonApiGaslessProvider&#x60;.  One provider instance handles every configured chain. When &#x60;chains&#x60; is omitted, &#x60;createFromContext&#x60; auto-registers every network the kit was configured with. */

public struct TONTonApiGaslessProviderConfig: Codable {

    /** Per-chain settings keyed by `Network#chainId`. */
    public var chains: [String: TONTonApiGaslessChainConfig]?
    /** Provider id. Defaults to `tonapi`. */
    public var providerId: String?
    /** Number of send retries on transient errors. Defaults to 5. */
    public var sendRetries: Int?
    /** Delay between send retries in ms. Defaults to 1000. */
    public var sendRetryDelayMs: Int?
    /** Number of quote retries on transient errors (5xx / network). Defaults to 5. */
    public var quoteRetries: Int?
    /** Fixed delay between quote retries in ms. Defaults to 1000. */
    public var quoteRetryDelayMs: Int?
    /** TTL for the in-memory `/v2/gasless/config` cache (ms). Defaults to 5 minutes. Set to `0` to disable caching. */
    public var configCacheTtlMs: Int?

    public init(chains: [String: TONTonApiGaslessChainConfig]? = nil, providerId: String? = nil, sendRetries: Int? = nil, sendRetryDelayMs: Int? = nil, quoteRetries: Int? = nil, quoteRetryDelayMs: Int? = nil, configCacheTtlMs: Int? = nil) {
        self.chains = chains
        self.providerId = providerId
        self.sendRetries = sendRetries
        self.sendRetryDelayMs = sendRetryDelayMs
        self.quoteRetries = quoteRetries
        self.quoteRetryDelayMs = quoteRetryDelayMs
        self.configCacheTtlMs = configCacheTtlMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chains
        case providerId
        case sendRetries
        case sendRetryDelayMs
        case quoteRetries
        case quoteRetryDelayMs
        case configCacheTtlMs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(chains, forKey: .chains)
        try container.encodeIfPresent(providerId, forKey: .providerId)
        try container.encodeIfPresent(sendRetries, forKey: .sendRetries)
        try container.encodeIfPresent(sendRetryDelayMs, forKey: .sendRetryDelayMs)
        try container.encodeIfPresent(quoteRetries, forKey: .quoteRetries)
        try container.encodeIfPresent(quoteRetryDelayMs, forKey: .quoteRetryDelayMs)
        try container.encodeIfPresent(configCacheTtlMs, forKey: .configCacheTtlMs)
    }
}




extension TONTonApiGaslessProviderConfig: JSValueCodable {}

