//
//  TONTransaction.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Transaction on the TON blockchain. */

public struct TONTransaction: Codable {

    public var account: TONUserFriendlyAddress
    public var accountStateBefore: TONTransactionAccountState?
    public var accountStateAfter: TONTransactionAccountState?
    public var description: TONTransactionDescription?
    public var hash: TONHex
    public var logicalTime: String
    /** Unix timestamp of the transaction */
    public var now: Double
    /** Masterchain block sequence number */
    public var mcBlockSeqno: Int
    public var traceExternalHash: TONHex
    /** ID of the trace */
    public var traceId: String?
    /** The hash of the previous transaction */
    public var previousTransactionHash: String?
    public var previousTransactionLogicalTime: String?
    public var origStatus: TONAccountStatus?
    public var endStatus: TONAccountStatus?
    public var totalFees: TONTokenAmount?
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var totalFeesExtraCurrencies: [String: String]?
    public var blockRef: TONTransactionBlockRef?
    public var inMessage: TONTransactionMessage?
    /** The list of outgoing messages produced by the transaction */
    public var outMessages: [TONTransactionMessage]
    /** Emulated state of the transaction */
    public var isEmulated: Bool

    public init(account: TONUserFriendlyAddress, accountStateBefore: TONTransactionAccountState? = nil, accountStateAfter: TONTransactionAccountState? = nil, description: TONTransactionDescription? = nil, hash: TONHex, logicalTime: String, now: Double, mcBlockSeqno: Int, traceExternalHash: TONHex, traceId: String? = nil, previousTransactionHash: String? = nil, previousTransactionLogicalTime: String? = nil, origStatus: TONAccountStatus? = nil, endStatus: TONAccountStatus? = nil, totalFees: TONTokenAmount? = nil, totalFeesExtraCurrencies: [String: String]? = nil, blockRef: TONTransactionBlockRef? = nil, inMessage: TONTransactionMessage? = nil, outMessages: [TONTransactionMessage], isEmulated: Bool) {
        self.account = account
        self.accountStateBefore = accountStateBefore
        self.accountStateAfter = accountStateAfter
        self.description = description
        self.hash = hash
        self.logicalTime = logicalTime
        self.now = now
        self.mcBlockSeqno = mcBlockSeqno
        self.traceExternalHash = traceExternalHash
        self.traceId = traceId
        self.previousTransactionHash = previousTransactionHash
        self.previousTransactionLogicalTime = previousTransactionLogicalTime
        self.origStatus = origStatus
        self.endStatus = endStatus
        self.totalFees = totalFees
        self.totalFeesExtraCurrencies = totalFeesExtraCurrencies
        self.blockRef = blockRef
        self.inMessage = inMessage
        self.outMessages = outMessages
        self.isEmulated = isEmulated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case accountStateBefore
        case accountStateAfter
        case description
        case hash
        case logicalTime
        case now
        case mcBlockSeqno
        case traceExternalHash
        case traceId
        case previousTransactionHash
        case previousTransactionLogicalTime
        case origStatus
        case endStatus
        case totalFees
        case totalFeesExtraCurrencies
        case blockRef
        case inMessage
        case outMessages
        case isEmulated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encodeIfPresent(accountStateBefore, forKey: .accountStateBefore)
        try container.encodeIfPresent(accountStateAfter, forKey: .accountStateAfter)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(hash, forKey: .hash)
        try container.encode(logicalTime, forKey: .logicalTime)
        try container.encode(now, forKey: .now)
        try container.encode(mcBlockSeqno, forKey: .mcBlockSeqno)
        try container.encode(traceExternalHash, forKey: .traceExternalHash)
        try container.encodeIfPresent(traceId, forKey: .traceId)
        try container.encodeIfPresent(previousTransactionHash, forKey: .previousTransactionHash)
        try container.encodeIfPresent(previousTransactionLogicalTime, forKey: .previousTransactionLogicalTime)
        try container.encodeIfPresent(origStatus, forKey: .origStatus)
        try container.encodeIfPresent(endStatus, forKey: .endStatus)
        try container.encodeIfPresent(totalFees, forKey: .totalFees)
        try container.encodeIfPresent(totalFeesExtraCurrencies, forKey: .totalFeesExtraCurrencies)
        try container.encodeIfPresent(blockRef, forKey: .blockRef)
        try container.encodeIfPresent(inMessage, forKey: .inMessage)
        try container.encode(outMessages, forKey: .outMessages)
        try container.encode(isEmulated, forKey: .isEmulated)
    }
}




extension TONTransaction: JSValueCodable {}

