//
//  TONTransactionComputePhase.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Compute phase of transaction execution (TVM execution). */

public struct TONTransactionComputePhase: Codable {

    /** The flag indicating if the compute phase was skipped */
    public var isSkipped: Bool?
    /** The success state of the compute phase */
    public var isSuccess: Bool?
    /** The flag indicating if message state was used */
    public var isMessageStateUsed: Bool?
    /** The flag indicating if the account was activated during compute */
    public var isAccountActivated: Bool?
    public var gasFees: TONTokenAmount?
    public var gasUsed: TONTokenAmount?
    public var gasLimit: TONTokenAmount?
    public var gasCredit: TONTokenAmount?
    /** The compute execution mode */
    public var mode: Int?
    /** The exit code returned from the VM */
    public var exitCode: Int?
    /** The number of steps executed by the VM */
    public var vmStepsNumber: Int?
    public var vmInitStateHash: TONHex?
    public var vmFinalStateHash: TONHex?

    public init(isSkipped: Bool? = nil, isSuccess: Bool? = nil, isMessageStateUsed: Bool? = nil, isAccountActivated: Bool? = nil, gasFees: TONTokenAmount? = nil, gasUsed: TONTokenAmount? = nil, gasLimit: TONTokenAmount? = nil, gasCredit: TONTokenAmount? = nil, mode: Int? = nil, exitCode: Int? = nil, vmStepsNumber: Int? = nil, vmInitStateHash: TONHex? = nil, vmFinalStateHash: TONHex? = nil) {
        self.isSkipped = isSkipped
        self.isSuccess = isSuccess
        self.isMessageStateUsed = isMessageStateUsed
        self.isAccountActivated = isAccountActivated
        self.gasFees = gasFees
        self.gasUsed = gasUsed
        self.gasLimit = gasLimit
        self.gasCredit = gasCredit
        self.mode = mode
        self.exitCode = exitCode
        self.vmStepsNumber = vmStepsNumber
        self.vmInitStateHash = vmInitStateHash
        self.vmFinalStateHash = vmFinalStateHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSkipped
        case isSuccess
        case isMessageStateUsed
        case isAccountActivated
        case gasFees
        case gasUsed
        case gasLimit
        case gasCredit
        case mode
        case exitCode
        case vmStepsNumber
        case vmInitStateHash
        case vmFinalStateHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isSkipped, forKey: .isSkipped)
        try container.encodeIfPresent(isSuccess, forKey: .isSuccess)
        try container.encodeIfPresent(isMessageStateUsed, forKey: .isMessageStateUsed)
        try container.encodeIfPresent(isAccountActivated, forKey: .isAccountActivated)
        try container.encodeIfPresent(gasFees, forKey: .gasFees)
        try container.encodeIfPresent(gasUsed, forKey: .gasUsed)
        try container.encodeIfPresent(gasLimit, forKey: .gasLimit)
        try container.encodeIfPresent(gasCredit, forKey: .gasCredit)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(exitCode, forKey: .exitCode)
        try container.encodeIfPresent(vmStepsNumber, forKey: .vmStepsNumber)
        try container.encodeIfPresent(vmInitStateHash, forKey: .vmInitStateHash)
        try container.encodeIfPresent(vmFinalStateHash, forKey: .vmFinalStateHash)
    }
}




extension TONTransactionComputePhase: JSValueCodable {}

