//
//  TONTransactionTokenInfo.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public enum TONTransactionTokenInfo: Codable {

    case jettonWallets(TONTransactionTokenInfoJettonWallets)
    case jettonMasters(TONTransactionTokenInfoJettonMasters)
    case unknown(TONTransactionTokenInfoBase)

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)
        switch type {

        case "jetton_wallets":
            let value = try container.decode(TONTransactionTokenInfoJettonWallets.self, forKey: .value)
            self = .jettonWallets(value)
        case "jetton_masters":
            let value = try container.decode(TONTransactionTokenInfoJettonMasters.self, forKey: .value)
            self = .jettonMasters(value)
        case "unknown":
            let value = try container.decode(TONTransactionTokenInfoBase.self, forKey: .value)
            self = .unknown(value)
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown type: \(type)"
            )
        }
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {

        case .jettonWallets(let value):
            try container.encode("jetton_wallets", forKey: .type)
            try container.encode(value, forKey: .value)
        case .jettonMasters(let value):
            try container.encode("jetton_masters", forKey: .type)
            try container.encode(value, forKey: .value)
        case .unknown(let value):
            try container.encode("unknown", forKey: .type)
            try container.encode(value, forKey: .value)
        }
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }
}



extension TONTransactionTokenInfo: JSValueCodable {}

