//
//  TONTransactionAction.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Action phase of transaction execution (message sending). */

public struct TONTransactionAction: Codable {

    /** The flag indicating whether the action phase succeeded */
    public var isSuccess: Bool?
    /** The flag indicating whether the action phase was valid */
    public var isValid: Bool?
    /** The flag indicating if the transaction had insufficient funds */
    public var hasNoFunds: Bool?
    /** The status change applied to the account during the action phase */
    public var statusChange: String?
    public var totalForwardingFees: TONTokenAmount?
    public var totalActionFees: TONTokenAmount?
    /** The result code returned from the action phase */
    public var resultCode: Int?
    /** The total number of actions processed */
    public var totalActionsNumber: Int?
    /** The number of special actions executed */
    public var specActionsNumber: Int?
    /** The number of skipped actions during execution */
    public var skippedActionsNumber: Int?
    /** The number of messages created in the action phase */
    public var messagesCreatedNumber: Int?
    public var actionListHash: TONHex?
    public var totalMessagesSize: TONTransactionActionMessageSize?

    public init(isSuccess: Bool? = nil, isValid: Bool? = nil, hasNoFunds: Bool? = nil, statusChange: String? = nil, totalForwardingFees: TONTokenAmount? = nil, totalActionFees: TONTokenAmount? = nil, resultCode: Int? = nil, totalActionsNumber: Int? = nil, specActionsNumber: Int? = nil, skippedActionsNumber: Int? = nil, messagesCreatedNumber: Int? = nil, actionListHash: TONHex? = nil, totalMessagesSize: TONTransactionActionMessageSize? = nil) {
        self.isSuccess = isSuccess
        self.isValid = isValid
        self.hasNoFunds = hasNoFunds
        self.statusChange = statusChange
        self.totalForwardingFees = totalForwardingFees
        self.totalActionFees = totalActionFees
        self.resultCode = resultCode
        self.totalActionsNumber = totalActionsNumber
        self.specActionsNumber = specActionsNumber
        self.skippedActionsNumber = skippedActionsNumber
        self.messagesCreatedNumber = messagesCreatedNumber
        self.actionListHash = actionListHash
        self.totalMessagesSize = totalMessagesSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSuccess
        case isValid
        case hasNoFunds
        case statusChange
        case totalForwardingFees
        case totalActionFees
        case resultCode
        case totalActionsNumber
        case specActionsNumber
        case skippedActionsNumber
        case messagesCreatedNumber
        case actionListHash
        case totalMessagesSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isSuccess, forKey: .isSuccess)
        try container.encodeIfPresent(isValid, forKey: .isValid)
        try container.encodeIfPresent(hasNoFunds, forKey: .hasNoFunds)
        try container.encodeIfPresent(statusChange, forKey: .statusChange)
        try container.encodeIfPresent(totalForwardingFees, forKey: .totalForwardingFees)
        try container.encodeIfPresent(totalActionFees, forKey: .totalActionFees)
        try container.encodeIfPresent(resultCode, forKey: .resultCode)
        try container.encodeIfPresent(totalActionsNumber, forKey: .totalActionsNumber)
        try container.encodeIfPresent(specActionsNumber, forKey: .specActionsNumber)
        try container.encodeIfPresent(skippedActionsNumber, forKey: .skippedActionsNumber)
        try container.encodeIfPresent(messagesCreatedNumber, forKey: .messagesCreatedNumber)
        try container.encodeIfPresent(actionListHash, forKey: .actionListHash)
        try container.encodeIfPresent(totalMessagesSize, forKey: .totalMessagesSize)
    }
}




extension TONTransactionAction: JSValueCodable {}

