//
//  TONTokenInfo.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Display information for a token (GRAM, Jetton, or NFT). */

public struct TONTokenInfo: Codable {

    /** Display name of the token */
    public var name: String?
    /** Human-readable description of the token */
    public var description: String?
    public var image: TONTokenImage?
    public var animation: TONTokenAnimation?
    /** Ticker symbol of the token (e.g., \"GRAM\", \"USDT\") */
    public var symbol: String?

    public init(name: String? = nil, description: String? = nil, image: TONTokenImage? = nil, animation: TONTokenAnimation? = nil, symbol: String? = nil) {
        self.name = name
        self.description = description
        self.image = image
        self.animation = animation
        self.symbol = symbol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case image
        case animation
        case symbol
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(animation, forKey: .animation)
        try container.encodeIfPresent(symbol, forKey: .symbol)
    }
}




extension TONTokenInfo: JSValueCodable {}

