//
//  TONTransactionMessage.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Message sent or received in a transaction. */

public struct TONTransactionMessage: Codable {

    public var hash: TONHex
    public var normalizedHash: TONHex?
    public var source: TONUserFriendlyAddress?
    public var destination: TONUserFriendlyAddress?
    public var value: TONTokenAmount?
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var valueExtraCurrencies: [String: String]?
    public var fwdFee: TONTokenAmount?
    public var creationLogicalTime: String?
    /** The timestamp when the message was created */
    public var createdAt: Double?
    /** The opcode included in the message payload */
    public var opcode: String?
    /** IHR(Immediate hypercube routing) enabled/disabled IHR is a method of message delivery in the TON Blockchain network, where messages are sent directly to the recipient’s shardchain. */
    public var ihrDisabled: Bool?
    public var ihrFee: TONTokenAmount?
    /** The flag indicating if the message requested a bounce on failure */
    public var isBounce: Bool?
    /** The flag indicating if the message was bounced back */
    public var isBounced: Bool?
    public var importFee: TONTokenAmount?
    public var messageContent: TONTransactionMessageContent?

    public init(hash: TONHex, normalizedHash: TONHex? = nil, source: TONUserFriendlyAddress? = nil, destination: TONUserFriendlyAddress? = nil, value: TONTokenAmount? = nil, valueExtraCurrencies: [String: String]? = nil, fwdFee: TONTokenAmount? = nil, creationLogicalTime: String? = nil, createdAt: Double? = nil, opcode: String? = nil, ihrDisabled: Bool? = nil, ihrFee: TONTokenAmount? = nil, isBounce: Bool? = nil, isBounced: Bool? = nil, importFee: TONTokenAmount? = nil, messageContent: TONTransactionMessageContent? = nil) {
        self.hash = hash
        self.normalizedHash = normalizedHash
        self.source = source
        self.destination = destination
        self.value = value
        self.valueExtraCurrencies = valueExtraCurrencies
        self.fwdFee = fwdFee
        self.creationLogicalTime = creationLogicalTime
        self.createdAt = createdAt
        self.opcode = opcode
        self.ihrDisabled = ihrDisabled
        self.ihrFee = ihrFee
        self.isBounce = isBounce
        self.isBounced = isBounced
        self.importFee = importFee
        self.messageContent = messageContent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hash
        case normalizedHash
        case source
        case destination
        case value
        case valueExtraCurrencies
        case fwdFee
        case creationLogicalTime
        case createdAt
        case opcode
        case ihrDisabled
        case ihrFee
        case isBounce
        case isBounced
        case importFee
        case messageContent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hash, forKey: .hash)
        try container.encodeIfPresent(normalizedHash, forKey: .normalizedHash)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(destination, forKey: .destination)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(valueExtraCurrencies, forKey: .valueExtraCurrencies)
        try container.encodeIfPresent(fwdFee, forKey: .fwdFee)
        try container.encodeIfPresent(creationLogicalTime, forKey: .creationLogicalTime)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(opcode, forKey: .opcode)
        try container.encodeIfPresent(ihrDisabled, forKey: .ihrDisabled)
        try container.encodeIfPresent(ihrFee, forKey: .ihrFee)
        try container.encodeIfPresent(isBounce, forKey: .isBounce)
        try container.encodeIfPresent(isBounced, forKey: .isBounced)
        try container.encodeIfPresent(importFee, forKey: .importFee)
        try container.encodeIfPresent(messageContent, forKey: .messageContent)
    }
}




extension TONTransactionMessage: JSValueCodable {}

