//
//  TONTransactionDescription.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Detailed description of transaction execution phases. */

public struct TONTransactionDescription: Codable {

    /** The transaction type (e.g., tick-tock, ord, split-prepare) */
    public var type: String
    /** The flag indicating if the transaction was aborted */
    public var isAborted: Bool
    /** The flag indicating if the account was destroyed */
    public var isDestroyed: Bool
    /** The flag indicating if the credit phase was executed first */
    public var isCreditFirst: Bool
    /** The flag indicating if this was a tock transaction */
    public var isTock: Bool
    /** The flag indicating if the contract was installed */
    public var isInstalled: Bool
    public var storagePhase: TONTransactionStoragePhase?
    public var creditPhase: TONTransactionCreditPhase?
    public var computePhase: TONTransactionComputePhase?
    public var action: TONTransactionAction?

    public init(type: String, isAborted: Bool, isDestroyed: Bool, isCreditFirst: Bool, isTock: Bool, isInstalled: Bool, storagePhase: TONTransactionStoragePhase? = nil, creditPhase: TONTransactionCreditPhase? = nil, computePhase: TONTransactionComputePhase? = nil, action: TONTransactionAction? = nil) {
        self.type = type
        self.isAborted = isAborted
        self.isDestroyed = isDestroyed
        self.isCreditFirst = isCreditFirst
        self.isTock = isTock
        self.isInstalled = isInstalled
        self.storagePhase = storagePhase
        self.creditPhase = creditPhase
        self.computePhase = computePhase
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case isAborted
        case isDestroyed
        case isCreditFirst
        case isTock
        case isInstalled
        case storagePhase
        case creditPhase
        case computePhase
        case action
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(isAborted, forKey: .isAborted)
        try container.encode(isDestroyed, forKey: .isDestroyed)
        try container.encode(isCreditFirst, forKey: .isCreditFirst)
        try container.encode(isTock, forKey: .isTock)
        try container.encode(isInstalled, forKey: .isInstalled)
        try container.encodeIfPresent(storagePhase, forKey: .storagePhase)
        try container.encodeIfPresent(creditPhase, forKey: .creditPhase)
        try container.encodeIfPresent(computePhase, forKey: .computePhase)
        try container.encodeIfPresent(action, forKey: .action)
    }
}




extension TONTransactionDescription: JSValueCodable {}

