//
//  TONTransactionTraceAction.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** High-level action extracted from a transaction trace. */

public struct TONTransactionTraceAction: Codable {

    /** Trace identifier */
    public var traceId: String?
    /** Action identifier */
    public var actionId: String?
    public var startLt: String?
    public var endLt: String?
    /** Unix time when the action started */
    public var startUtime: Double?
    /** Unix time when the action ended */
    public var endUtime: Int?
    public var traceEndLt: String?
    /** Unix time when the trace ended */
    public var traceEndUtime: Int?
    /** Masterchain block sequence number when the trace ended */
    public var traceMcSeqnoEnd: Double?
    /** List of transaction hashes involved in this action */
    public var transactions: [TONHex]
    /** Indicates if the action was successful */
    public var isSuccess: Bool?
    public var traceExternalHash: TONHex?
    /** List of accounts involved in this action */
    public var accounts: [TONUserFriendlyAddress]
    public var details: TONTransactionTraceActionDetails

    public init(traceId: String? = nil, actionId: String? = nil, startLt: String? = nil, endLt: String? = nil, startUtime: Double? = nil, endUtime: Int? = nil, traceEndLt: String? = nil, traceEndUtime: Int? = nil, traceMcSeqnoEnd: Double? = nil, transactions: [TONHex], isSuccess: Bool? = nil, traceExternalHash: TONHex? = nil, accounts: [TONUserFriendlyAddress], details: TONTransactionTraceActionDetails) {
        self.traceId = traceId
        self.actionId = actionId
        self.startLt = startLt
        self.endLt = endLt
        self.startUtime = startUtime
        self.endUtime = endUtime
        self.traceEndLt = traceEndLt
        self.traceEndUtime = traceEndUtime
        self.traceMcSeqnoEnd = traceMcSeqnoEnd
        self.transactions = transactions
        self.isSuccess = isSuccess
        self.traceExternalHash = traceExternalHash
        self.accounts = accounts
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case traceId
        case actionId
        case startLt
        case endLt
        case startUtime
        case endUtime
        case traceEndLt
        case traceEndUtime
        case traceMcSeqnoEnd
        case transactions
        case isSuccess
        case traceExternalHash
        case accounts
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(traceId, forKey: .traceId)
        try container.encodeIfPresent(actionId, forKey: .actionId)
        try container.encodeIfPresent(startLt, forKey: .startLt)
        try container.encodeIfPresent(endLt, forKey: .endLt)
        try container.encodeIfPresent(startUtime, forKey: .startUtime)
        try container.encodeIfPresent(endUtime, forKey: .endUtime)
        try container.encodeIfPresent(traceEndLt, forKey: .traceEndLt)
        try container.encodeIfPresent(traceEndUtime, forKey: .traceEndUtime)
        try container.encodeIfPresent(traceMcSeqnoEnd, forKey: .traceMcSeqnoEnd)
        try container.encode(transactions, forKey: .transactions)
        try container.encodeIfPresent(isSuccess, forKey: .isSuccess)
        try container.encodeIfPresent(traceExternalHash, forKey: .traceExternalHash)
        try container.encode(accounts, forKey: .accounts)
        try container.encode(details, forKey: .details)
    }
}




extension TONTransactionTraceAction: JSValueCodable {}

