//
//  TONTransactionTraceMoneyFlow.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Summary of token flows for a transaction. */

public struct TONTransactionTraceMoneyFlow: Codable {

    public var outputs: TONTokenAmount
    public var inputs: TONTokenAmount
    /** List of all token transfers involved in the transaction */
    public var allJettonTransfers: [TONTransactionTraceMoneyFlowItem]
    /** List of token transfers involving our address */
    public var ourTransfers: [TONTransactionTraceMoneyFlowItem]
    public var ourAddress: TONUserFriendlyAddress?

    public init(outputs: TONTokenAmount, inputs: TONTokenAmount, allJettonTransfers: [TONTransactionTraceMoneyFlowItem], ourTransfers: [TONTransactionTraceMoneyFlowItem], ourAddress: TONUserFriendlyAddress? = nil) {
        self.outputs = outputs
        self.inputs = inputs
        self.allJettonTransfers = allJettonTransfers
        self.ourTransfers = ourTransfers
        self.ourAddress = ourAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outputs
        case inputs
        case allJettonTransfers
        case ourTransfers
        case ourAddress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(outputs, forKey: .outputs)
        try container.encode(inputs, forKey: .inputs)
        try container.encode(allJettonTransfers, forKey: .allJettonTransfers)
        try container.encode(ourTransfers, forKey: .ourTransfers)
        try container.encodeIfPresent(ourAddress, forKey: .ourAddress)
    }
}




extension TONTransactionTraceMoneyFlow: JSValueCodable {}

