//
//  TONTransactionsUpdate.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt


public struct TONTransactionsUpdate: Codable {

    public var status: TONStreamingUpdateStatus
    public var address: TONUserFriendlyAddress
    /** The array of transactions */
    public var transactions: [TONTransaction]
    public var traceHash: TONHex
    /** Map of raw addresses to their metadata entries. */
    public var addressBook: [String: TONAddressBookEntry]?
    /** Metadata about addresses, including indexing and associated token info. */
    public var metadata: [String: TONTransactionAddressMetadataEntry]?
    public let type: String

    public init(status: TONStreamingUpdateStatus, address: TONUserFriendlyAddress, transactions: [TONTransaction], traceHash: TONHex, addressBook: [String: TONAddressBookEntry]? = nil, metadata: [String: TONTransactionAddressMetadataEntry]? = nil) {
        self.type = "transactions"
        self.status = status
        self.address = address
        self.transactions = transactions
        self.traceHash = traceHash
        self.addressBook = addressBook
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case status
        case address
        case transactions
        case traceHash
        case addressBook
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(status, forKey: .status)
        try container.encode(address, forKey: .address)
        try container.encode(transactions, forKey: .transactions)
        try container.encode(traceHash, forKey: .traceHash)
        try container.encodeIfPresent(addressBook, forKey: .addressBook)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}




extension TONTransactionsUpdate: JSValueCodable {}

