//
//  TONTransactionRequest.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

/** Request to send a transaction on the TON blockchain. Contains &#x60;messages&#x60; or &#x60;items&#x60;. If items are present, but messages are not — wallet app is responsible for resolving items into messages. */

public struct TONTransactionRequest: Codable {

    /** List of messages to include in the transaction */
    public var messages: [TONTransactionRequestMessage]
    /** List of structured items (ton/jetton/nft) as an alternative to raw messages. When present, the wallet app is responsible for resolving items into messages. */
    public var items: [TONStructuredItem]?
    public var network: TONNetwork?
    /** Unix timestamp after which the transaction becomes invalid */
    public var validUntil: Double?
    /** Sender wallet address in received format(raw, user friendly) */
    public var fromAddress: String?

    public init(messages: [TONTransactionRequestMessage], items: [TONStructuredItem]? = nil, network: TONNetwork? = nil, validUntil: Double? = nil, fromAddress: String? = nil) {
        self.messages = messages
        self.items = items
        self.network = network
        self.validUntil = validUntil
        self.fromAddress = fromAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
        case items
        case network
        case validUntil
        case fromAddress
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messages, forKey: .messages)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(network, forKey: .network)
        try container.encodeIfPresent(validUntil, forKey: .validUntil)
        try container.encodeIfPresent(fromAddress, forKey: .fromAddress)
    }
}




extension TONTransactionRequest: JSValueCodable {}

