//
//  TONTransactionTraceActionDetails.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import _BigInt

public enum TONTransactionTraceActionDetails: Codable {

    case jettonSwap(TONTransactionTraceActionJettonSwapDetails)
    case callContract(TONTransactionTraceActionCallContractDetails)
    case tonTransfer(TONTransactionTraceActionTONTransferDetails)
    case unknown([String: AnyCodable])

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)
        switch type {

        case "jetton_swap":
            let value = try container.decode(TONTransactionTraceActionJettonSwapDetails.self, forKey: .value)
            self = .jettonSwap(value)
        case "call_contract":
            let value = try container.decode(TONTransactionTraceActionCallContractDetails.self, forKey: .value)
            self = .callContract(value)
        case "ton_transfer":
            let value = try container.decode(TONTransactionTraceActionTONTransferDetails.self, forKey: .value)
            self = .tonTransfer(value)
        case "unknown":
            let value = try container.decode([String: AnyCodable].self, forKey: .value)
            self = .unknown(value)
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown type: \(type)"
            )
        }
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {

        case .jettonSwap(let value):
            try container.encode("jetton_swap", forKey: .type)
            try container.encode(value, forKey: .value)
        case .callContract(let value):
            try container.encode("call_contract", forKey: .type)
            try container.encode(value, forKey: .value)
        case .tonTransfer(let value):
            try container.encode("ton_transfer", forKey: .type)
            try container.encode(value, forKey: .value)
        case .unknown(let value):
            try container.encode("unknown", forKey: .type)
            try container.encode(value, forKey: .value)
        }
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }
}



extension TONTransactionTraceActionDetails: JSValueCodable {}

