//
//  TONDiscriminatedUnionWithFormat.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
import Foundation
import _BigInt
public enum TONDiscriminatedUnionWithFormat: Codable {
    case a(TONDiscriminatedUnionWithFormatA)
    case b(code: UInt16)
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .discriminator)
        switch discriminator {
        case "a":
            self = .a(try TONDiscriminatedUnionWithFormatA(from: decoder))
        case "b":
            let code = try container.decode(UInt16.self, forKey: .code)
            self = .b(code: code)
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .discriminator,
                in: container,
                debugDescription: "Unknown discriminator value: \(discriminator)"
            )
        }
    }
    public func encode(to encoder: any Encoder) throws {
        switch self {
        case .a(let value):
            try value.encode(to: encoder)
        case .b(let code):
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode("b", forKey: .discriminator)
            try container.encode(code, forKey: .code)
        }
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discriminator = "type"
        case code
    }
}
extension TONDiscriminatedUnionWithFormat: JSValueCodable {}
