//
//  TONIntegerFormatsCase.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
import Foundation
import _BigInt
public struct TONIntegerFormatsCase: Codable {
    public var intField: Int
    public var int8Field: Int8
    public var int16Field: Int16
    public var int32Field: Int32
    public var int64Field: Int64
    public var uintField: UInt
    public var uint8Field: UInt8
    public var uint16Field: UInt16
    public var uint32Field: UInt32
    public var uint64Field: UInt64
    public var timestampField: Int
    public init(intField: Int, int8Field: Int8, int16Field: Int16, int32Field: Int32, int64Field: Int64, uintField: UInt, uint8Field: UInt8, uint16Field: UInt16, uint32Field: UInt32, uint64Field: UInt64, timestampField: Int) {
        self.intField = intField
        self.int8Field = int8Field
        self.int16Field = int16Field
        self.int32Field = int32Field
        self.int64Field = int64Field
        self.uintField = uintField
        self.uint8Field = uint8Field
        self.uint16Field = uint16Field
        self.uint32Field = uint32Field
        self.uint64Field = uint64Field
        self.timestampField = timestampField
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case intField
        case int8Field
        case int16Field
        case int32Field
        case int64Field
        case uintField
        case uint8Field
        case uint16Field
        case uint32Field
        case uint64Field
        case timestampField
    }
    // Encodable protocol methods
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(intField, forKey: .intField)
        try container.encode(int8Field, forKey: .int8Field)
        try container.encode(int16Field, forKey: .int16Field)
        try container.encode(int32Field, forKey: .int32Field)
        try container.encode(int64Field, forKey: .int64Field)
        try container.encode(uintField, forKey: .uintField)
        try container.encode(uint8Field, forKey: .uint8Field)
        try container.encode(uint16Field, forKey: .uint16Field)
        try container.encode(uint32Field, forKey: .uint32Field)
        try container.encode(uint64Field, forKey: .uint64Field)
        try container.encode(timestampField, forKey: .timestampField)
    }
}
extension TONIntegerFormatsCase: JSValueCodable {}
