//
//  TONPropertyKindsCase.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
import Foundation
import _BigInt
public struct TONPropertyKindsCase: Codable {
    public var requiredString: String
    public var optionalString: String?
    public var nullableString: String?
    public var requiredCount: Int32
    public var isActive: Bool
    public var tags: [String]
    public var nestedEnums: [TONBasicNumericEnum]
    public var metadata: [String: String]
    public init(requiredString: String, optionalString: String? = nil, nullableString: String?, requiredCount: Int32, isActive: Bool, tags: [String], nestedEnums: [TONBasicNumericEnum], metadata: [String: String]) {
        self.requiredString = requiredString
        self.optionalString = optionalString
        self.nullableString = nullableString
        self.requiredCount = requiredCount
        self.isActive = isActive
        self.tags = tags
        self.nestedEnums = nestedEnums
        self.metadata = metadata
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requiredString
        case optionalString
        case nullableString
        case requiredCount
        case isActive
        case tags
        case nestedEnums
        case metadata
    }
    // Encodable protocol methods
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requiredString, forKey: .requiredString)
        try container.encodeIfPresent(optionalString, forKey: .optionalString)
        try container.encode(nullableString, forKey: .nullableString)
        try container.encode(requiredCount, forKey: .requiredCount)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(tags, forKey: .tags)
        try container.encode(nestedEnums, forKey: .nestedEnums)
        try container.encode(metadata, forKey: .metadata)
    }
}
extension TONPropertyKindsCase: JSValueCodable {}
